Repository ember-template-lint/ember-template-lint, pull requests merged in 2019-11, with the labels that each got.

#870 Fix issue preventing running a subset of rules
  lib/index.js
  test/acceptance-test.js
  test/fixtures/rules-subset-disabled/application.hbs
  test/fixtures/rules-subset-disabled/temp-templatelint-rc.js
  test/fixtures/rules-subset/temp-templatelint-rc.js
  test/fixtures/rules-subset/template.hbs
  test/unit/bin/ember-template-lint-test.js
Labels: bug

#884 Fix `no-curly-component-invocation` to not warn about invocations within an existing angle bracket invocation
  lib/rules/lint-no-curly-component-invocation.js
  test/unit/rules/lint-no-curly-component-invocation-test.js
Labels: bug

#890 Remove TransformDotComponentInvocation.
  lib/index.js
  lib/plugins/transform-dot-component-invocation.js
  lib/rules/lint-attribute-indentation.js
  lib/rules/lint-block-indentation.js
  test/unit/rules/lint-no-implicit-this-test.js
Labels: internal

#892 Remove reliance on `preprocess` (from `@glimmer/syntax`) ability to accept an array of AST plugins
  lib/index.js
  test/unit/rules/lint-no-trailing-dot-in-path-expression-test.js
Labels: internal

#865 Add new `no-args-paths` rule.
  docs/rule/no-args-paths.md
  docs/rule/no-curly-component-invocation.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/lint-no-args-paths.js
  test/unit/rules/lint-no-args-paths-test.js
Labels: enhancement

#893 Add `no-args-paths` to the `octane` preset
  lib/config/octane.js
Labels: enhancement

#896 Pass `moduleName` and `rawSource` to `Rule` upon creation.
  lib/index.js
  lib/rules/base.js
  lib/rules/lint-no-attrs-in-components.js
  lib/rules/lint-no-outlet-outside-routes.js
  test/unit/base-plugin-test.js
Labels: internal

#850 Changed parser mode to 'codemod'
  lib/index.js
  lib/rules/lint-block-indentation.js
  lib/rules/lint-linebreak-style.js
  lib/rules/lint-no-bare-strings.js
  test/unit/rules/lint-block-indentation-test.js
  test/unit/rules/lint-linebreak-style-test.js
  test/unit/rules/lint-no-bare-strings-test.js
Labels: enhancement

#885 Drop support for NodeJs v6 and v11
  .travis.yml
  README.md
  package.json
Labels: breaking

#898 Update dependencies to latest (requiring Node 8+).
  package.json
  yarn.lock
Labels: internal

#844 Remove HTML comment config
  lib/rules/base.js
Labels: breaking

#873 Leverage ember-template-recast
  lib/index.js
  package.json
  test/unit/base-plugin-test.js
  test/unit/helpers/ast-node-info-test.js
  test/unit/helpers/is-interactive-element-test.js
  test/unit/linting-compiler-test.js
  test/unit/rules/lint-no-inline-styles-test.js
  yarn.lock
Labels: Blocked on Node 6, enhancement

#900 Remove deprecated rule `img-alt-attributes` (replaced by `require-valid-alt-text`)
  docs/rule/img-alt-attributes.md
  docs/rules.md
  lib/config/0-8-recommended.js
  lib/config/1-x-recommended.js
  lib/rules/index.js
  lib/rules/lint-img-alt-attributes.js
  test/unit/rules/lint-img-alt-attributes-test.js
Labels: breaking

#902 Do not validate indentation within `<pre>`,`<script>`, or `<style>`.
  lib/rules/lint-block-indentation.js
  test/unit/rules/lint-block-indentation-test.js
Labels: bug

#876 Begin migrating tests to inline fixtures (via `broccoli-test-helper`)
  package.json
  test/acceptance-test.js
  test/fixtures/config-in-root/.template-lintrc.js
  test/fixtures/config-in-root/app/templates/application.hbs
  test/fixtures/config-with-parse-error/.template-lintrc.js
  test/fixtures/deprecated-rule-config/.template-lintrc.js
  test/unit/get-config-test.js
  yarn.lock
Labels: internal

#904 Update `block-indentation` to ignore children of `<template>` and `<textarea>`
  lib/rules/lint-block-indentation.js
  test/unit/rules/lint-block-indentation-test.js
Labels: bug

#905 Ensure configuration ordering does not matter with `no-bare-strings`
  lib/rules/lint-no-bare-strings.js
  test/unit/rules/lint-no-bare-strings-test.js
Labels: bug

#908 Update `no-bare-strings` to ignore contents within elements that are not translated (e.g. `<script>`,`<style>`, and `<pre>`).
  lib/rules/lint-no-bare-strings.js
  test/unit/rules/lint-no-bare-strings-test.js
Labels: bug

#906 Add utility function to allow reading from `.editorconfig`
  lib/get-editor-config.js
  lib/helpers/rule-test-harness.js
  lib/index.js
  lib/rules/base.js
  package.json
  test/unit/get-editor-config-test.js
Labels: enhancement

#919 Use `.editorconfig` to choose default value for `linebreak-style`
  docs/rule/linebreak-style.md
  lib/rules/lint-linebreak-style.js
  test/unit/rules/lint-linebreak-style-test.js
Labels: breaking, enhancement

#918 Use `.editorconfig` to choose default value for `block-indentation`
  docs/rule/block-indentation.md
  lib/rules/lint-block-indentation.js
  test/unit/rules/lint-block-indentation-test.js
Labels: breaking, enhancement

#913 Update `no-unnecessary-component-helper` rule to allow the `component` helper as an angle bracket component argument
  docs/rule/no-unnecessary-component-helper.md
  lib/rules/lint-no-unnecessary-component-helper.js
  test/unit/rules/lint-no-unnecessary-component-helper-test.js
Labels: bug

#920 Ensure `no-bare-strings` consider literals in mustaches (e.g. `{{"foo"}}`)
  lib/rules/lint-no-bare-strings.js
  test/unit/rules/lint-no-bare-strings-test.js
Labels: bug

#932 Move main linter engine to stand alone file.
  lib/index.js
  lib/linter.js
Labels: internal

#933 Linter class: Use named severity
  lib/linter.js
Labels: internal

#941 Leverage static class fields for SEVERITY constants
  lib/index.js
  lib/linter.js
Labels: internal

#951 Implement `no-multiple-empty-lines` rule
  docs/rule/no-multiple-empty-lines.md
  docs/rules.md
  lib/rules/base.js
  lib/rules/index.js
  lib/rules/lint-no-multiple-empty-lines.js
  test/unit/rules/lint-no-multiple-empty-lines-test.js
Labels: enhancement

#950 Implement `require-button-type` rule
  docs/rule/require-button-type.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/lint-require-button-type.js
  test/unit/rules/lint-require-button-type-test.js
Labels: enhancement

#963 Update lockfile
  yarn.lock
Labels: internal

#965 Improve ESLint setup
  .eslintrc.js
  .gitignore
  bin/.eslintrc.js
  lib/.eslintrc.js
  package.json
Labels: internal

#967 test/bin: Use `execa` to run CLI for tests
  package.json
  test/unit/bin/ember-template-lint-test.js
Labels: internal

#959 Add validation that all files in `lib/config/` have been reexported in `lib/config/index.js`
  test/unit/base-plugin-test.js
Labels: internal

#970 Remove unused `mocha-only-detector` dev dependency
  package.json
  yarn.lock
Labels: internal

#964 Implement `no-passed-in-event-handlers` rule
  docs/rule/no-passed-in-event-handlers.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-passed-in-event-handlers.js
  test/unit/rules/no-passed-in-event-handlers-test.js
Labels: enhancement

#968 Replace Mocha with Jest
  .travis.yml
  package.json
  test/mocha.opts
  test/unit/bin/ember-template-lint-test.js
  test/unit/get-config-test.js
  test/unit/rules/no-trailing-dot-in-path-expression-test.js
  yarn.lock
Labels: internal

#969 test/get-config: Remove pointless test
  test/unit/get-config-test.js
Labels: internal

#952 Add GitHub Actions CI workflow
  .github/workflows/ci.yml
Labels: internal
