Repository ember-template-lint/ember-template-lint, pull requests merged in 2019-10, with the labels that each got.

#846 Update `table-groups` to enforce required ordering of table children
  lib/rules/lint-table-groups.js
  test/unit/rules/lint-table-groups-test.js
Labels: bug

#783 Add support for reading a file to lint from `process.stdin` (e.g `cat some-file.hbs | ember-template-lint`)
  README.md
  bin/ember-template-lint.js
  test/fixtures/stdin-with-errors/.template-lintrc.js
  test/fixtures/stdin-with-errors/app/templates/application.hbs
  test/unit/bin/ember-template-lint-test.js
Labels: enhancement

#849 Improve `require-valid-alt-text` rule to catch additional common failure scenarios
  docs/rule/require-valid-alt-text.md
  lib/rules/lint-require-valid-alt-text.js
  test/unit/rules/lint-require-valid-alt-text-test.js
Labels: bug

#853 Add `no-action` rule
  docs/rule/no-action-modifiers.md
  docs/rule/no-action.md
  docs/rule/no-element-event-actions.md
  docs/rules.md
  lib/helpers/rule-test-harness.js
  lib/rules/index.js
  lib/rules/lint-no-action.js
  test/unit/rules/lint-no-action-test.js
Labels: enhancement

#858 Add `no-action` to `octane` preset configuration.
  lib/config/octane.js
Labels: enhancement

#859 Remove `testem` setup.
  package.json
  testem.js
Labels: internal

#861 Update `no-curly-component-invocation` to allow non-component yielded values to be used with mustaches
  lib/rules/lint-no-curly-component-invocation.js
  test/unit/rules/lint-no-curly-component-invocation-test.js
Labels: bug

#862 ✨Add option --print-pending from ember-cli-template-lint
  README.md
  bin/ember-template-lint.js
  test/unit/bin/ember-template-lint-test.js
Labels: enhancement

#882 Fix issues when converting dasherized curly component invocation into angle bracket invocation
  lib/helpers/curly-component-invocation.js
  test/unit/helpers/curly-invocation-component-test.js
Labels: bug

#887 Ensure `no-action` does not error when encountering literals (StringLiteral, BooleanLiteral, etc).
  lib/rules/internal/scope.js
  lib/rules/lint-no-action.js
  test/unit/rules/lint-no-action-test.js
Labels: bug

#819 Added `no-whitespace-for-layout` rule
  docs/rule/no-whitespace-for-layout.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/lint-no-whitespace-for-layout.js
  test/unit/rules/lint-no-whitespace-for-layout-test.js
Labels: enhancement

#868 Add `no-meta-redirect-with-time-limit` rule
  docs/rule/no-meta-redirect-with-time-limit.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/lint-no-meta-redirect-with-time-limit.js
  test/unit/rules/lint-no-meta-redirect-with-time-limit-test.js
Labels: enhancement

#848 Add `no-whitespace-within-word` rule
  docs/rule/no-whitespace-within-word.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/lint-no-whitespace-within-word.js
  test/unit/rules/lint-no-whitespace-within-word-test.js
Labels: enhancement
