Repository ember-template-lint/ember-template-lint, pull requests merged in 2019-12, with the labels that each got.

#973 Remove TravisCI configuration file
  .travis.yml
Labels: internal

#972 Replace `chai` with Jest assertions
  .eslintrc.js
  package.json
  test/acceptance-test.js
  test/unit/base-plugin-test.js
  test/unit/bin/ember-template-lint-test.js
  test/unit/default-config-test.js
  test/unit/get-config-test.js
  test/unit/helpers/ast-node-info-test.js
  test/unit/helpers/curly-invocation-component-test.js
  test/unit/helpers/is-interactive-element-test.js
  test/unit/linting-compiler-test.js
  test/unit/recommended-config-test.js
  yarn.lock
Labels: internal

#971 no-curly-component-invocation: Do not warn for MustacheStatements with positional arguments
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: enhancement

#979 Update `.npmignore` file
  .npmignore
Labels: internal

#986 no-multiple-empty-lines: Fix `parseConfig()` implementation
  lib/rules/no-multiple-empty-lines.js
  test/unit/rules/no-multiple-empty-lines-test.js
Labels: bug

#980 Add `no-invalid-role` rule
  docs/rule/no-invalid-role.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-invalid-role.js
  test/unit/rules/no-invalid-role-test.js
Labels: a11y, enhancement

#930 updated `require-valid-alt-text` to check for common a11y failure #39
  docs/rule/require-valid-alt-text.md
  lib/rules/require-valid-alt-text.js
  test/unit/rules/require-valid-alt-text-test.js
Labels: enhancement

#934 Support parsing a `--fix` flag
  bin/ember-template-lint.js
  test/unit/bin/ember-template-lint-test.js
Labels: enhancement

#966 Report errors as GitHub Actions Annotations
  bin/ember-template-lint.js
  lib/index.js
  test/unit/bin/ember-template-lint-test.js
  test/unit/github-actions-test.js
Labels: enhancement

#993 updated rule to cover orientation lock failure
  docs/rule/no-invalid-meta.md
  lib/rules/no-invalid-meta.js
  test/unit/rules/no-invalid-meta-test.js
Labels: a11y, enhancement

#910 Add `no-invalid-meta` rule
  docs/rule/no-invalid-meta.md
  docs/rule/no-meta-redirect-with-time-limit.md
  docs/rules.md
  lib/helpers/deprecated-rules.js
  lib/rules/index.js
  lib/rules/no-invalid-meta.js
  test/unit/rules/no-invalid-meta-test.js
Labels: a11y, enhancement

#988 Add rule `no-invalid-link-text`
  docs/rule/no-invalid-link-text.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-invalid-link-text.js
  test/unit/rules/no-invalid-link-text-test.js
Labels: a11y, enhancement

#997 Add `require-button-type` to octane configuration
  lib/config/octane.js
Labels: enhancement

#994 Use `Template` and `Block` nodes instead of `Program` fallback
  lib/rules/base.js
  lib/rules/eol-last.js
  lib/rules/no-multiple-empty-lines.js
  lib/rules/no-trailing-spaces.js
  lib/rules/no-unused-block-params.js
  lib/rules/template-length.js
  test/unit/base-plugin-test.js
Labels: internal

#999 Fix Changelog
  CHANGELOG.md
Labels: documentation

#1000 package.json: Fix repository URLs
  package.json
Labels: documentation

#1002 no-whitespace-for-layout: Ignore whitespace at the start and end of the line
  lib/rules/no-whitespace-for-layout.js
  test/unit/rules/no-whitespace-for-layout-test.js
Labels: bug

#977 updated README to include a semantic versioning policy
  README.md
  dev/versioning.md
Labels: documentation

#1005 no-curly-component-invocation: Ignore block invocations with inverse blocks
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: bug

#1006 no-curly-component-invocation: Ignore *all* curly invocations with positional arguments
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: bug

#1009 Ensure `require-valid-alt-text` does not flag `<img ...attributes>`.
  lib/rules/require-valid-alt-text.js
  test/unit/rules/require-valid-alt-text-test.js
Labels: bug

#1007 Extract `FakeConsole` class to simplify testing code
  test/acceptance-test.js
  test/helpers/console.js
  test/unit/get-config-test.js
Labels: internal

#1010 Add `no-yield-only` rule
  docs/rule/no-yield-only.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-yield-only.js
  test/unit/rules/no-yield-only-test.js
Labels: enhancement

#1008 Extract `Printer` classes
  bin/ember-template-lint.js
  lib/index.js
  lib/printers/default.js
  lib/printers/github-actions.js
  lib/printers/json.js
  lib/printers/pretty.js
  test/acceptance-test.js
  test/printers/pretty-test.js
  test/unit/github-actions-test.js
Labels: internal

#1013 Fix missing `Linter.errorsToMessages()` API for ember-cli-template-lint
  lib/index.js
  lib/printers/pretty.js
  test/acceptance-test.js
  test/printers/pretty-test.js
Labels: bug

#1011 Add test cases for `{{!-- template-lint-disable --}}` comments
  lib/helpers/rule-test-harness.js
Labels: internal

#1024 Upgrade ember-template-recast
  package.json
  test/unit/rules/no-inline-styles-test.js
  yarn.lock
Labels: dependencies

#1027 no-curly-component-invocation: Fix false positives
  docs/rule/no-curly-component-invocation.md
  lib/config/octane.js
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: bug

#1031 no-passed-in-event-handlers: Ignore built-in `input` and `textarea` components
  lib/rules/no-passed-in-event-handlers.js
  test/unit/rules/no-passed-in-event-handlers-test.js
Labels: bug

#1032 no-curly-component-invocation: Ignore built-ins and fix nested key scoped variable scenario
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: bug
