Repository ember-template-lint/ember-template-lint, pull requests merged in 2019-01, with the labels that each got.

#580 Rejects invalid configPath configuration
  bin/ember-template-lint.js
  lib/get-config.js
  test/acceptance-test.js
Labels: bug

#591 feat: update 'style-concatenation' rule to catch an unsafe usage of the 'concat' helper.
  docs/rule/style-concatenation.md
  lib/helpers/ast-node-info.js
  lib/rules/lint-style-concatenation.js
  test/unit/rules/lint-style-concatenation-test.js
Labels: bug

#597 Fix config resolution with Yarn PnP.
  lib/get-config.js
Labels: bug

#598 Add lerna-changelog for changelog generation.
  package.json
  yarn.lock
Labels: enhancement

#599 Remove attribute-indentation from recommended config.
  lib/config/recommended.js
Labels: breaking

#600 Add {{welcome-page}} to default allowed list for no-implicit-this.
  lib/rules/lint-no-implicit-this.js
  test/unit/rules/lint-no-implicit-this-test.js
Labels: enhancement

#573 Allow RegExp's with no-implicit-this
  docs/rule/no-implicit-this.md
  lib/rules/lint-no-implicit-this.js
  test/fixtures/no-implicit-this-allow-with-regexp/.template-lintrc.js
  test/fixtures/no-implicit-this-allow-with-regexp/app/templates/application.hbs
  test/unit/rules/lint-no-implicit-this-test.js
Labels: enhancement

#559 Added video and audio with control attribute as interactive elements
  lib/helpers/is-interactive-element.js
  test/unit/helpers/is-interactive-element-test.js
Labels: bug

#613 fix: avoid suggesting 'unless' with helpers in condition in 'no-negated-condition' rule.
  lib/rules/lint-no-negated-condition.js
  test/unit/rules/lint-no-negated-condition.js
Labels: bug

#614 feat: add new rule 'no-element-event-actions'.
  docs/rule/no-element-event-actions.md
  docs/rules.md
  lib/helpers/ast-node-info.js
  lib/rules/index.js
  lib/rules/lint-no-element-event-actions.js
  test/unit/rules/lint-no-element-event-actions-test.js
Labels: enhancement

#639 fix: Whitelisted empty bare string causes an infinite loop #429
  lib/rules/lint-no-bare-strings.js
  test/unit/rules/lint-no-bare-strings-test.js
Labels: bug
