Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-05, with the labels that each got.

#1317 Avoid glob matching when no-glob is present (e.g. globs have already been replaced by shell expansion)
  README.md
  bin/ember-template-lint.js
  package.json
  test/unit/bin/expand-file-globs-test.js
  yarn.lock
Labels: bug

#1323 Refactor `no-invalid-role` rule to better support future additions
  lib/rules/no-invalid-role.js
  test/unit/rules/no-invalid-role-test.js
Labels: internal

#1320 Add `catchNonexistentRoles` option (default false) to `no-invalid-role` rule
  docs/rule/no-invalid-role.md
  lib/rules/no-invalid-role.js
  test/unit/rules/no-invalid-role-test.js
Labels: enhancement

#927 Add `no-arguments-for-html-elements` rule
  docs/rule/no-arguments-for-html-elements.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-arguments-for-html-elements.js
  test/unit/rules/no-arguments-for-html-elements-test.js
Labels: enhancement

#1333 Ensure `<MyComponent @prop={{can.do}} />` triggers `no-implicit-this` error.
  test/unit/rules/no-implicit-this-test.js
Labels: internal

#1338 Clarify recommended fix for `no-negated-condition` rule
  docs/rule/no-negated-condition.md
  lib/rules/no-negated-condition.js
Labels: documentation

#1322 Add new rule: `no-nested-landmark`
  docs/rule/no-nested-landmark.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-nested-landmark.js
  test/unit/rules/no-nested-landmark-test.js
Labels: enhancement

#1321 Add new rule: `no-redundant-landmark-role`
  docs/rule/no-redundant-landmark-role.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-redundant-landmark-role.js
  test/unit/rules/no-redundant-landmark-role-test.js
Labels: enhancement

#1335 Add new rule: no-forbidden-elements
  docs/rule/no-forbidden-elements.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-forbidden-elements.js
  test/unit/rules/no-forbidden-elements-test.js
Labels: enhancement

#1347 bugfix: `no-implicit-this` rule allows built-in helpers
  lib/rules/no-implicit-this.js
  test/unit/rules/no-implicit-this-test.js
Labels: bug

#1355 Add a test for fixing from stdin (povided a --filename is given)
  test/acceptance/editors-integration-test.js
Labels: internal

#1362 Handle `unless` in `no-positive-tabindex` rule
  lib/rules/no-positive-tabindex.js
  test/unit/rules/no-positive-tabindex-test.js
Labels: bug
