Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-04, with the labels that each got.

#1238 Add new rule: `require-form-method`
  docs/rule/require-form-method.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/require-form-method.js
  test/unit/rules/require-form-method-test.js
Labels: enhancement

#1250 Update each rule doc to mention what config enables the rule
  README.md
  docs/rule/block-indentation.md
  docs/rule/deprecations/deprecated-render-helper.md
  docs/rule/eol-last.md
  docs/rule/linebreak-style.md
  docs/rule/link-href-attributes.md
  docs/rule/link-rel-noopener.md
  docs/rule/no-abstract-roles.md
  docs/rule/no-action.md
  docs/rule/no-args-paths.md
  docs/rule/no-attrs-in-components.md
  docs/rule/no-curly-component-invocation.md
  docs/rule/no-debugger.md
  docs/rule/no-duplicate-attributes.md
  docs/rule/no-extra-mut-helper-argument.md
  docs/rule/no-html-comments.md
  docs/rule/no-implicit-this.md
  docs/rule/no-index-component-invocation.md
  docs/rule/no-inline-styles.md
  docs/rule/no-input-block.md
  docs/rule/no-input-tagname.md
  docs/rule/no-invalid-interactive.md
  docs/rule/no-invalid-link-text.md
  docs/rule/no-invalid-meta.md
  docs/rule/no-invalid-role.md
  docs/rule/no-log.md
  docs/rule/no-multiple-empty-lines.md
  docs/rule/no-negated-condition.md
  docs/rule/no-nested-interactive.md
  docs/rule/no-obsolete-elements.md
  docs/rule/no-outlet-outside-routes.md
  docs/rule/no-partial.md
  docs/rule/no-positive-tabindex.md
  docs/rule/no-quoteless-attributes.md
  docs/rule/no-shadowed-elements.md
  docs/rule/no-trailing-spaces.md
  docs/rule/no-triple-curlies.md
  docs/rule/no-unbound.md
  docs/rule/no-unnecessary-component-helper.md
  docs/rule/no-unnecessary-concat.md
  docs/rule/no-unused-block-params.md
  docs/rule/quotes.md
  docs/rule/require-button-type.md
  docs/rule/require-iframe-title.md
  docs/rule/require-valid-alt-text.md
  docs/rule/self-closing-void-elements.md
  docs/rule/simple-unless.md
  docs/rule/style-concatenation.md
  docs/rule/table-groups.md
  test/unit/rule-setup-test.js
Labels: documentation

#1251 Pass env from template-recast's transform callback to rules
  lib/linter.js
  lib/rules/base.js
  test/unit/base-plugin-test.js
Labels: enhancement

#1260 Expose `ember-template-recast` API on main entry point (e.g. `require('ember-template-lint').recast`)
  lib/index.js
Labels: enhancement

#1266 Bump GH actions/checkout to v2
  .github/workflows/ci.yml
Labels: internal

#1264 fix(--json): Add missing boolean type
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
Labels: bug

#1265 test(cli): Set LC_ALL env var to en_US
  test/acceptance/cli-test.js
Labels: internal

#1270 Start testing editor integrations
  test/acceptance/cli-test.js
  test/acceptance/editors-integration-test.js
  test/helpers/setup-env-var.js
Labels: internal

#1277 Use get-stdin dependency to read from stdin
  bin/ember-template-lint.js
  package.json
  yarn.lock
Labels: internal

#1278 Use the correct title in generated rule doc when running `yarn new`
  dev/new-rule/index.js
Labels: internal

#1263 Add `--rule` and `--no-config-path` command line options
  README.md
  bin/ember-template-lint.js
  lib/get-config.js
  lib/linter.js
  test/acceptance/cli-test.js
  test/unit/get-config-test.js
Labels: enhancement

#1282 Adapt tests for reading from stdin to run on Windows
  test/acceptance/cli-test.js
  test/acceptance/editors-integration-test.js
Labels: internal

#1309 Add Node 14 to CI.
  .github/workflows/ci.yml
Labels: internal

#1310 Refactor CI setup.
  .github/workflows/ci.yml
  package.json
Labels: internal

#1298 Add shell-specific tests for reading from stdin
  test/acceptance/stdin-by-platform-test.js
Labels: internal

#1222 Add new rule: no-unbalanced-curlies
  docs/rule/no-unbalanced-curlies.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-unbalanced-curlies.js
  test/unit/rules/no-unbalanced-curlies-test.js
Labels: enhancement

#1313 Update documentation and examples for `no-positive-tabindex`
  docs/rule/no-positive-tabindex.md
Labels: documentation
