Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-09, with the labels that each got.

#1466 fix: cache pending/ignore config lookups for faster perf/less memory
  lib/-private/module-status-cache.js
  lib/get-config.js
  lib/linter.js
  test/unit/-private/module-status-cache-test.js
  test/unit/get-config-test.js
Labels: enhancement

#1490 remove deprecated `whitelist` & `blacklist` configurations
  .eslintrc.js
  README.md
  docs/rule/no-bare-strings.md
  docs/rule/no-invalid-interactive.md
  docs/rule/no-nested-interactive.md
  docs/rule/simple-unless.md
  lib/helpers/parse-interactive-element-config.js
  lib/rules/no-bare-strings.js
  lib/rules/no-curly-component-invocation.js
  lib/rules/no-whitespace-within-word.js
  lib/rules/simple-unless.js
  test/unit/rules/no-bare-strings-test.js
  test/unit/rules/simple-unless-test.js
Labels: breaking

#1504 Update documentation for `no-duplicate-attributes`
  docs/rule/no-duplicate-attributes.md
Labels: documentation, enhancement

#1505 Update a11y config file
  lib/config/a11y.js
Labels: enhancement, internal

#1187 Adds new rule: no-duplicate-id
  README.md
  docs/rule/no-duplicate-id.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-duplicate-id.js
  test/unit/rules/no-duplicate-id-test.js
Labels: enhancement

#1509 Add `no-duplicate-id` to `a11y` preset
  lib/config/a11y.js
Labels: breaking

#1510 Update automated release setup.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#1514 Ensure `bad` test cases **always** have results.
  lib/helpers/rule-test-harness.js
Labels: bug

#1513 Fix `extends` overriding order
  lib/get-config.js
  test/fixtures/with-multiple-extends/.template-lintrc.js
  test/fixtures/with-plugins-overwriting/.template-lintrc.js
Labels: breaking, bug

#1525 Add new rule `require-each-key`
  README.md
  docs/rule/require-each-key.md
  lib/rules/index.js
  lib/rules/require-each-key.js
  test/unit/rules/require-each-key-test.js
Labels: enhancement

#1465 Add new rule `builtin-component-arguments`
  README.md
  docs/rule/builtin-component-arguments.md
  lib/rules/builtin-component-arguments.js
  lib/rules/index.js
  test/unit/rules/builtin-component-arguments-test.js
Labels: enhancement

#1533 Add missing `keygen` element to `no-obsolete-elements` rule elements list
  lib/rules/no-obsolete-elements.js
  test/unit/rules/no-obsolete-elements-test.js
Labels: bug

#1521 Add new rule `no-aria-hidden-body`
  README.md
  docs/rule/no-aria-hidden-body.md
  lib/rules/index.js
  lib/rules/no-aria-hidden-body.js
  test/unit/rules/no-aria-hidden-body-test.js
Labels: enhancement

#1537 Remove unnecessary deprecations folder for rules
  README.md
  docs/rule/deprecated-each-syntax.md
  docs/rule/deprecated-inline-view-helper.md
  docs/rule/deprecated-render-helper.md
  lib/rules/deprecated-each-syntax.js
  lib/rules/deprecated-inline-view-helper.js
  lib/rules/deprecated-render-helper.js
  lib/rules/index.js
  scripts/update-rules.js
  test/helpers/is-rule-fixable.js
  test/unit/rule-setup-test.js
  test/unit/rules/deprecated-each-syntax-test.js
  test/unit/rules/deprecated-inline-view-helper-test.js
  test/unit/rules/deprecated-render-helper-test.js
Labels: internal

#1534 Enable `catchNonexistentRoles` by default on `no-invalid-role` rule
  docs/rule/no-invalid-role.md
  lib/rules/no-invalid-role.js
  test/unit/rules/no-invalid-role-test.js
Labels: breaking

#1535 Remove support for deprecated rule names
  lib/helpers/deprecated-rules.js
Labels: breaking

#1543 Ignore comments in `no-invalid-block-param-definition` rule
  lib/rules/no-invalid-block-param-definition.js
  test/unit/rules/no-invalid-block-param-definition-test.js
Labels: bug

#1540 `require-input-label` rule should ignore hidden inputs
  docs/rule/require-input-label.md
  lib/rules/require-input-label.js
  test/unit/rules/require-input-label-test.js
Labels: bug

#1516 `no-whitespace-within-word` rule should ignore <style> elements
  lib/rules/no-whitespace-within-word.js
  test/unit/rules/no-whitespace-within-word-test.js
Labels: bug

#1532 Add `s` and `u` elements to `no-obsolete-elements` rule elements list
  docs/rule/no-obsolete-elements.md
  lib/rules/no-obsolete-elements.js
Labels: breaking

#1541 Allow nested landmarks of different types in `no-nested-landmark` rule
  docs/rule/no-nested-landmark.md
  lib/rules/no-nested-landmark.js
  test/unit/rules/no-nested-landmark-test.js
Labels: bug
