Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-06, with the labels that each got.

#1350 Add eslint-plugin-unicorn with recommended rules
  .eslintrc.js
  bin/ember-template-lint.js
  dev/new-rule/index.js
  lib/get-config.js
  lib/get-editor-config.js
  lib/helpers/curly-component-invocation.js
  lib/helpers/is-angle-bracket-component.js
  lib/helpers/is-interactive-element.js
  lib/helpers/rule-test-harness.js
  lib/rules/attribute-indentation.js
  lib/rules/base.js
  lib/rules/block-indentation.js
  lib/rules/deprecations/deprecated-inline-view-helper.js
  lib/rules/eol-last.js
  lib/rules/internal/scope.js
  lib/rules/linebreak-style.js
  lib/rules/no-abstract-roles.js
  lib/rules/no-bare-strings.js
  lib/rules/no-curly-component-invocation.js
  lib/rules/no-heading-inside-button.js
  lib/rules/no-input-tagname.js
  lib/rules/no-invalid-block-param-definition.js
  lib/rules/no-invalid-interactive.js
  lib/rules/no-invalid-link-text.js
  lib/rules/no-invalid-meta.js
  lib/rules/no-invalid-role.js
  lib/rules/no-multiple-empty-lines.js
  lib/rules/no-nested-interactive.js
  lib/rules/no-nested-landmark.js
  lib/rules/no-passed-in-event-handlers.js
  lib/rules/no-positive-tabindex.js
  lib/rules/no-unbalanced-curlies.js
  lib/rules/no-whitespace-within-word.js
  lib/rules/quotes.js
  lib/rules/require-input-label.js
  lib/rules/require-valid-alt-text.js
  lib/rules/self-closing-void-elements.js
  lib/rules/table-groups.js
  package.json
  test/acceptance/public-api-test.js
  test/unit/get-config-test.js
  test/unit/github-actions-test.js
  test/unit/recommended-config-test.js
  test/unit/rule-setup-test.js
  yarn.lock
Labels: internal

#1369 `invocable-blacklist` rule should disallow empty blacklist config array
  lib/rules/invocable-blacklist.js
  test/unit/rules/invocable-blacklist-test.js
Labels: bug

#1370 Update `invocable-blacklist` rule to handle nested angle bracket component invocation
  docs/rule/invocable-blacklist.md
  lib/helpers/dasherize-component-name.js
  lib/rules/invocable-blacklist.js
  test/unit/rules/invocable-blacklist-test.js
Labels: bug

#1372 Allow specifying a custom error message in `invocable-blacklist` rule
  docs/rule/invocable-blacklist.md
  lib/rules/invocable-blacklist.js
  test/unit/rules/invocable-blacklist-test.js
Labels: enhancement

#1387 Improve message for `no-implicit-this` to mention using angle bracket invocation
  lib/rules/no-implicit-this.js
  test/acceptance/public-api-test.js
Labels: documentation

#1393 Fix table groups ordering enforcement when whitespace is present in `table-groups` rule
  docs/rule/table-groups.md
  lib/rules/table-groups.js
  test/unit/rules/table-groups-test.js
Labels: bug

#1392 Add configuration options for allowing components as table children in `table-groups` rule
  docs/rule/table-groups.md
  lib/helpers/dasherize-component-name.js
  lib/helpers/is-dasherized-component-or-helper-name.js
  lib/helpers/javascript.js
  lib/rules/no-restricted-invocations.js
  lib/rules/table-groups.js
  test/unit/helpers/javascript-test.js
  test/unit/rules/table-groups-test.js
Labels: enhancement

#1394 Add autogenerated rule table for README
  .github/workflows/ci.yml
  README.md
  dev/new-rule/index.js
  docs/rules.md
  package.json
  scripts/update-rules.js
  test/unit/rule-setup-test.js
Labels: documentation

#1400 Refactor `no-restricted-invocations` rule to significantly improve performance
  lib/rules/no-restricted-invocations.js
  test/unit/rules/no-restricted-invocations-test.js
Labels: enhancement
