Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-08, with the labels that each got.

#1431 Add `--no-inline-config` option.
  README.md
  bin/ember-template-lint.js
  lib/linter.js
  lib/rules/base.js
  test/acceptance/cli-test.js
  test/unit/base-plugin-test.js
Labels: enhancement

#1436 Add note about github actions printer
  README.md
Labels: documentation

#1447 Replace `npm-package-json-lint` with `sort-package-json`
  .npmpackagejsonlintrc.json
  package.json
  yarn.lock
Labels: internal

#1316 Add new rule: `no-positional-data-test-selectors`
  README.md
  docs/rule/no-positional-data-test-selectors.md
  lib/rules/index.js
  lib/rules/no-positional-data-test-selectors.js
  test/unit/rules/no-positional-data-test-selectors-test.js
Labels: enhancement

#1452 Drop support for Node 13
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#1450 Implement `no-redundant-fn` rule
  README.md
  docs/rule/no-redundant-fn.md
  lib/rules/index.js
  lib/rules/no-redundant-fn.js
  test/unit/rules/no-redundant-fn-test.js
Labels: enhancement

#1449 Implement `no-nested-splattributes` rule
  README.md
  docs/rule/no-nested-splattributes.md
  lib/rules/index.js
  lib/rules/no-nested-splattributes.js
  test/unit/rules/no-nested-splattributes-test.js
Labels: enhancement

#1454 Fix misspelling of `--print-pending`s help output
  README.md
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
Labels: documentation

#1136 Update `no-curly-component-invocation` rule to ignore ember-cli-app-version usage
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: bug

#1455 Add test to ensure rules list is sorted
  lib/rules/index.js
  test/unit/rule-setup-test.js
Labels: internal

#1456 no-arguments-for-html-elements: Remove wrong examples from the documentation
  docs/rule/no-arguments-for-html-elements.md
Labels: documentation

#1457 Implement `no-potential-path-strings` rule
  README.md
  docs/rule/no-potential-path-strings.md
  lib/rules/index.js
  lib/rules/no-potential-path-strings.js
  test/unit/rules/no-potential-path-strings-test.js
Labels: enhancement

#1458 no-arguments-for-html-elements: Extract `no-block-params-for-html-elements` rule
  README.md
  docs/rule/no-arguments-for-html-elements.md
  docs/rule/no-block-params-for-html-elements.md
  lib/rules/index.js
  lib/rules/no-arguments-for-html-elements.js
  lib/rules/no-block-params-for-html-elements.js
  test/unit/rules/no-arguments-for-html-elements-test.js
  test/unit/rules/no-block-params-for-html-elements-test.js
Labels: enhancement

#1459 Implement `no-link-to-tag-name` rule
  README.md
  docs/rule/no-link-to-tag-name.md
  lib/rules/index.js
  lib/rules/no-link-to-tag-name.js
  test/unit/rules/no-link-to-tag-name-test.js
Labels: enhancement

#1461 no-invalid-interactive: Add `canvas` to the list of interactive tag names
  lib/helpers/is-interactive-element.js
  test/unit/rules/no-invalid-interactive-test.js
Labels: enhancement

#1462 no-invalid-interactive: Only warn about known disallowed DOM events in the `on` modifier
  lib/rules/no-invalid-interactive.js
  test/unit/rules/no-invalid-interactive-test.js
Labels: enhancement

#1467 Adjust `new-rule` template
  dev/new-rule/templates/test.js
Labels: internal

#1469 no-link-to-tag-name: Rename to `no-link-to-tagname`
  README.md
  docs/rule/no-link-to-tagname.md
  lib/rules/index.js
  lib/rules/no-link-to-tagname.js
  test/unit/rules/no-link-to-tagname-test.js
Labels: enhancement

#1474 Add `--fix` support for `link-rel-noopener` rule
  README.md
  docs/rule/link-rel-noopener.md
  lib/rules/link-rel-noopener.js
  test/unit/rules/link-rel-noopener-test.js
Labels: enhancement

#1464 no-quoteless-attributes: Adjust error message for component arguments
  lib/rules/no-quoteless-attributes.js
  test/unit/rules/no-quoteless-attributes-test.js
Labels: enhancement

#1439 Update `require-input-label` rule to detect duplicate labels
  lib/rules/require-input-label.js
  test/unit/rules/require-input-label-test.js
Labels: enhancement

#1443 Add new `a11y` configuration
  dev/versioning.md
  lib/config/a11y.js
  lib/config/index.js
Labels: enhancement

#1460 ast-node-info: Remove trivial `isElement()` helpers
  docs/plugins.md
  lib/helpers/ast-node-info.js
  lib/rules/link-href-attributes.js
  lib/rules/link-rel-noopener.js
  lib/rules/require-valid-alt-text.js
  test/unit/helpers/ast-node-info-test.js
Labels: breaking

#1463 ast-node-info: Remove trivial `isNode()` helpers
  docs/plugins.md
  lib/helpers/ast-node-info.js
  lib/helpers/is-interactive-element.js
  lib/rules/block-indentation.js
  lib/rules/link-rel-noopener.js
  lib/rules/no-element-event-actions.js
  lib/rules/no-inline-styles.js
  lib/rules/no-invalid-link-text.js
  lib/rules/no-invalid-link-title.js
  lib/rules/no-negated-condition.js
  lib/rules/no-unnecessary-component-helper.js
  lib/rules/style-concatenation.js
Labels: breaking
