Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-10, with the labels that each got.

#1553 Convert `Linter.prototype.verify` and `Linter.prototype.verifyAndFix` to be async.
  README.md
  bin/ember-template-lint.js
  lib/helpers/rule-test-harness.js
  lib/linter.js
  test/acceptance/public-api-test.js
  test/unit/recommended-config-test.js
Labels: breaking

#1232 Add `.html` to supported file extensions
  bin/ember-template-lint.js
  test/acceptance/public-api-test.js
Labels: breaking, enhancement

#1549 Add `<textarea>` and `<select>` support to `require-input-label` rule
  docs/rule/require-input-label.md
  lib/rules/require-input-label.js
  test/unit/rules/require-input-label-test.js
Labels: breaking, enhancement

#1554 Ensure globbing is only used when using a globlike pattern.
  bin/ember-template-lint.js
  package.json
  test/unit/bin/expand-file-globs-test.js
Labels: bug

#1556 Allow linting individual files with arbitrary extensions.
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
  test/unit/bin/expand-file-globs-test.js
  test/unit/bin/get-files-to-lint-test.js
Labels: enhancement

#1550 Adds new rule: `no-duplicate-landmark-elements`
  README.md
  docs/rule/no-duplicate-landmark-elements.md
  lib/config/a11y.js
  lib/rules/index.js
  lib/rules/no-duplicate-landmark-elements.js
  test/unit/rules/no-duplicate-landmark-elements-test.js
Labels: enhancement

#1564 Add `--working-directory` option.
  bin/ember-template-lint.js
  lib/-private/module-status-cache.js
  lib/get-config.js
  lib/get-editor-config.js
  lib/linter.js
  test/acceptance/cli-test.js
  test/unit/-private/module-status-cache-test.js
  test/unit/base-plugin-test.js
  test/unit/bin/expand-file-globs-test.js
  test/unit/bin/get-files-to-lint-test.js
  test/unit/get-config-test.js
Labels: enhancement

#1566 Allow `itemprop` use in meta tags in `no-invalid-meta` rule
  lib/rules/no-invalid-meta.js
  test/unit/rules/no-invalid-meta-test.js
Labels: bug

#1137 Prevent `no-unused-block-params` from flagging locals that are used within `{{template-lint-disable}}`ed content
  lib/rules/base.js
  lib/rules/internal/scope.js
  lib/rules/no-unused-block-params.js
  test/unit/rules/no-unused-block-params-test.js
Labels: bug

#1586 Add `no-aria-hidden-body` and `table-groups` to A11Y config
  lib/config/a11y.js
Labels: breaking
