Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-07, with the labels that each got.

#1410 Minor adjustement to README
  README.md
Labels: documentation

#1409 Add documentation: how to create a fixer for a rule
  README.md
  docs/fixer.md
Labels: documentation

#1411 README's rules list: Add 🔧 emoji to fixable rules
  .npmignore
  README.md
  package.json
  scripts/update-rules.js
  yarn.lock
Labels: documentation

#1413 Add fixable notice to the rule doc of fixable rules
  docs/rule/inline-link-to.md
  docs/rule/require-button-type.md
  scripts/update-rules.js
  test/helpers/is-rule-fixable.js
  test/unit/rule-setup-test.js
Labels: documentation

#1407 get-config: Do not mutate the configuration's `plugins` key
  lib/get-config.js
  test/unit/get-config-test.js
Labels: bug

#1418 Add npm-package-json-lint
  .npmpackagejsonlintrc.json
  package.json
  yarn.lock
Labels: internal

#1426 Add v8-compile-cache to improve startup performance
  bin/ember-template-lint.js
  package.json
  yarn.lock
Labels: enhancement

#1386 Add new rule: `require-lang-attribute`
  README.md
  docs/rule/require-lang-attribute.md
  lib/rules/index.js
  lib/rules/require-lang-attribute.js
  test/unit/rules/require-lang-attribute-test.js
Labels: enhancement
