Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-03, with the labels that each got.

#1181 Ensure the exported class name matches the rule name
  .eslintrc.js
  lib/helpers/is-interactive-element.js
  lib/rules/attribute-indentation.js
  lib/rules/base.js
  lib/rules/linebreak-style.js
  lib/rules/no-args-paths.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-bare-strings.js
  lib/rules/no-duplicate-attributes.js
  lib/rules/no-extra-mut-helper-argument.js
  lib/rules/no-html-comments.js
  lib/rules/no-implicit-this.js
  lib/rules/no-index-component-invocation.js
  lib/rules/no-inline-styles.js
  lib/rules/no-invalid-interactive.js
  lib/rules/no-nested-interactive.js
  lib/rules/no-triple-curlies.js
  lib/rules/no-unused-block-params.js
  lib/rules/no-yield-only.js
  lib/rules/require-iframe-title.js
  lib/rules/require-valid-alt-text.js
  lib/rules/self-closing-void-elements.js
  lib/rules/simple-unless.js
  lib/rules/style-concatenation.js
  lib/rules/template-length.js
Labels: internal

#1183 --fix: Write output to fs
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
Labels: enhancement

#1185 Add message about running `--fix` to console output when fixable errors have ocurred.
  lib/printers/pretty.js
  test/acceptance/cli-test.js
Labels: enhancement

#1188 updates the `createNewRuleDocFile` function
  dev/new-rule/index.js
Labels: internal

#1189 Ensure resolvable plugins work when the config is not resolved.
  lib/get-config.js
  test/unit/get-config-test.js
Labels: bug

#1190 Ensure BOM is preserved when using `--fix`.
  lib/linter.js
  package.json
  test/acceptance/public-api-test.js
Labels: enhancement

#1184 .template-lintrc.js: Resolve ember-template-lint-plugin-* packages
  docs/plugins.md
  lib/get-config.js
  test/unit/get-config-test.js
Labels: enhancement

#1191 Refactor printers.
  bin/ember-template-lint.js
  lib/helpers/process-results.js
  lib/printers/default.js
  lib/printers/github-actions.js
  lib/printers/json.js
  lib/printers/pretty.js
  test/acceptance/cli-test.js
Labels: internal

#1195 Add v2 migration guide
  CHANGELOG.md
  docs/migration/v2.md
Labels: documentation

#1160 Add severity support (off, warn, error) to rule configuration (via both `.template-lintrc.js` and inline configuration).
  README.md
  lib/config/0-8-recommended.js
  lib/config/1-x-recommended.js
  lib/config/octane.js
  lib/config/recommended.js
  lib/config/stylistic.js
  lib/get-config.js
  lib/helpers/rule-test-harness.js
  lib/linter.js
  lib/rules/base.js
  test/acceptance/public-api-test.js
  test/fixtures/config/disable-all.js
  test/fixtures/no-implicit-this-allow-with-regexp/.template-lintrc.js
  test/fixtures/with-inline-plugins/.template-lintrc.js
  test/fixtures/with-plugins/.template-lintrc.js
  test/unit/base-plugin-test.js
  test/unit/get-config-test.js
  test/unit/rules/block-indentation-test.js
Labels: enhancement

#1196 Migrate to `yargs` for argument parsing.
  bin/ember-template-lint.js
  package.json
  test/acceptance/cli-test.js
  test/unit/bin-test.js
  yarn.lock
Labels: internal

#1179 inline-link-to: Implement `fix` mode
  lib/rules/inline-link-to.js
  test/unit/rules/inline-link-to-test.js
Labels: enhancement

#1202 Update contributing info in README
  README.md
Labels: documentation

#1200 Add `--ignore-pattern` and `--no-ignore-pattern` command line flags
  README.md
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
Labels: enhancement

#1210 bugfix: flase-positive rule for invalid block param definition
  lib/rules/no-invalid-block-param-definition.js
  test/unit/rules/no-invalid-block-param-definition-test.js
Labels: bug

#1220 Ensure each rule documentation file has the right title and an examples section
  docs/rule/attribute-indentation.md
  docs/rule/eol-last.md
  docs/rule/linebreak-style.md
  docs/rule/no-abstract-roles.md
  docs/rule/no-implicit-this.md
  docs/rule/quotes.md
  docs/rule/require-input-label.md
  docs/rule/require-valid-alt-text.md
  docs/rule/template-length.md
  test/unit/base-plugin-test.js
Labels: documentation

#1229 Ensure template parsing errors are only reported once (not once per-rule)
  lib/linter.js
  test/acceptance/public-api-test.js
Labels: bug
