Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-01, with the labels that each got.

#1036 Group acceptance tests in test/acceptance folder
  test/acceptance/cli-test.js
  test/acceptance/public-api-test.js
  test/unit/bin-test.js
Labels: internal

#1042 Refactor test-harness
  lib/helpers/rule-test-harness.js
Labels: internal

#1023 Drop NodeJs v8 support
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking, internal

#1045 Remove no-implicit-this from `recommended` config.
  lib/config/recommended.js
Labels: enhancement

#1046 Update `octane` config to extend from `recommended`.
  lib/config/octane.js
Labels: internal

#1047 Add `no-args-path`, `no-invalid-link-text`, `no-invalid-meta`, `require-button-type` into `recommended` configuration.
  lib/config/octane.js
  lib/config/recommended.js
Labels: breaking

#1048 Add `stylistic` configuration
  lib/config/index.js
  lib/config/stylistic.js
Labels: enhancement

#1049 Bring `no-implicit-this` back into the `octane` config
  lib/config/octane.js
Labels: bug

#1050 Add presets list to README
  README.md
Labels: documentation

#1051 Fix configuration of `quotes` rule in `stylistic` preset
  lib/config/stylistic.js
Labels: bug

#1054 Remove deprecated rule `no-meta-redirect-with-time-limit` which was replaced by `no-invalid-meta`
  docs/rule/no-meta-redirect-with-time-limit.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-meta-redirect-with-time-limit.js
  test/unit/rules/no-meta-redirect-with-time-limit-test.js
Labels: breaking

#1055 Remove deprecated array config for `no-nested-interactive` rule
  lib/rules/no-nested-interactive.js
  test/unit/rules/no-nested-interactive-test.js
Labels: breaking

#1052 Change `allowDynamicStyles` option to default to true in `no-inline-styles` rule
  docs/rule/no-inline-styles.md
  lib/rules/no-inline-styles.js
  test/unit/rules/no-inline-styles-test.js
Labels: breaking

#1053 Add `no-invalid-role` and `no-negated-condition` rules to `recommended` preset
  lib/config/recommended.js
Labels: breaking, enhancement

#895 Add `no-index-component-invocation` rule
  docs/rule/no-index-component-invocation.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-index-component-invocation.js
  test/unit/rules/no-index-component-invocation-test.js
Labels: enhancement

#1059 Add `no-index-component-invocation` to `recommended` configuration.
  lib/config/recommended.js
Labels: breaking

#1061 Remove deprecated rule `no-trailing-dot-in-path-expression`
  docs/rule/no-trailing-dot-in-path-expression.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-trailing-dot-in-path-expression.js
  test/unit/rules/no-trailing-dot-in-path-expression-test.js
Labels: breaking

#1062 Add support for detecting `eol-last` from `.editorconfig`
  docs/rule/eol-last.md
  lib/rules/eol-last.js
  test/unit/rules/eol-last-test.js
Labels: enhancement

#1060 Add more rules to `stylistic` config
  README.md
  lib/config/stylistic.js
Labels: breaking, enhancement

#1067 Remove deprecated `templateEnvironmentData` rule property
  lib/rules/base.js
Labels: breaking

#1068 no-curly-component-invocation: Document default config
  docs/rule/no-curly-component-invocation.md
Labels: documentation

#1070 Update most dependencies to latest
  package.json
  yarn.lock
Labels: dependencies

#1071 Update `no-invalid-interactive` to allow `change` event with `<form>` elements
  lib/rules/no-invalid-interactive.js
  test/unit/rules/no-invalid-interactive-test.js
Labels: bug

#1081 Fix some spelling mistakes
  CHANGELOG.md
  docs/rule/no-curly-component-invocation.md
  docs/rule/no-whitespace-within-word.md
  docs/rule/require-valid-alt-text.md
  lib/helpers/curly-component-invocation.js
  lib/helpers/rule-test-harness.js
  lib/rules/link-rel-noopener.js
  lib/rules/no-duplicate-attributes.js
  lib/rules/simple-unless.js
  test/acceptance/public-api-test.js
Labels: documentation

#1083 Add presets list to README
  README.md
Labels: documentation

#1069 Remove deprecated rules
  lib/helpers/deprecated-rules.js
  test/acceptance/public-api-test.js
  test/unit/rules/no-bare-strings-test.js
  test/unit/rules/no-html-comments-test.js
  test/unit/rules/no-triple-curlies-test.js
  test/unit/rules/no-unused-block-params-test.js
Labels: breaking, internal

#1087 Fix crash from missing `content` attribute in `no-invalid-meta` rule
  docs/rule/no-invalid-meta.md
  lib/rules/no-invalid-meta.js
  test/unit/rules/no-invalid-meta-test.js
Labels: bug

#1090 Update `no-curly-component-invocation` rule to ignore all usages of the `yield` helper
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: bug

#1094 docs/plugins: Fix typo
  docs/plugins.md
Labels: documentation

#1078 Add `modifier-name-case` rule
  docs/rule/modifier-name-case.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/modifier-name-case.js
  test/unit/rules/modifier-name-case-test.js
Labels: enhancement
