Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-02, with the labels that each got.

#1108 Update `no-bare-strings` rule to allow `&ndash;`
  lib/rules/no-bare-strings.js
  test/unit/rules/no-bare-strings-test.js
Labels: bug

#1088 Update `no-invalid-meta` rule to catch incorrect meta attribute combinations
  docs/rule/no-invalid-meta.md
  lib/rules/no-invalid-meta.js
  test/unit/rules/no-invalid-meta-test.js
Labels: breaking, enhancement

#1107 Simplify a few rules by using the `path` visitor argument
  lib/rules/no-action-modifiers.js
  lib/rules/no-bare-strings.js
  lib/rules/no-curly-component-invocation.js
Labels: internal

#1121 Update dependencies to latest allowed versions.
  package.json
  yarn.lock
Labels: internal

#1086 Update `block-indentation` rule to add new `ignoreComments` option
  docs/rule/block-indentation.md
  lib/rules/block-indentation.js
  test/unit/rules/block-indentation-test.js
Labels: enhancement

#1123 Fix issues introduced by ember-template-recast@4.0.1.
  lib/rules/no-quoteless-attributes.js
  lib/rules/quotes.js
  package.json
  test/unit/base-plugin-test.js
  test/unit/rules/quotes-test.js
  yarn.lock
Labels: bug

#1133 Don't mention `ember-cli-template-lint` in README
  README.md
Labels: documentation

#1134 Add `ignoredTags` option to `no-invalid-interactive` rule
  lib/rules/no-invalid-interactive.js
  test/unit/rules/no-invalid-interactive-test.js
Labels: enhancement

#1138 Automatically discover `.template-lintrc.js` when running linter from a project subdirectory (e.g. a monorepo's package, with linting configuration in the project root).
  lib/get-config.js
  package.json
  test/acceptance/public-api-test.js
Labels: enhancement

#1126 Add new rule `no-invalid-block-param-definition`
  docs/rule/no-invalid-block-param-definition.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-invalid-block-param-definition.js
  test/unit/rules/no-invalid-block-param-definition-test.js
Labels: enhancement

#1146 Update execa from 1.x to 4.0.0.
  package.json
  test/acceptance/cli-test.js
  yarn.lock
Labels: internal

#1147 Use updated mechanism to disable chalk.
  test/acceptance/public-api-test.js
  test/printers/pretty-test.js
Labels: internal

#1148 Use npm-run-all to run multiple scripts.
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: internal

#935 Implement more plumbing for `--fix` support (add `Linter.prototype.verifyAndFix`)
  bin/ember-template-lint.js
  lib/linter.js
  test/acceptance/public-api-test.js
Labels: enhancement

#1151 Add internal `fixturify-project` based test helper.
  package.json
  test/acceptance/public-api-test.js
  test/helpers/fake-project.js
  test/unit/get-config-test.js
  test/unit/get-editor-config-test.js
  yarn.lock
Labels: internal

#1153 Ensure plugins are resolved relative to config file location.
  lib/get-config.js
  test/helpers/fake-project.js
  test/unit/get-config-test.js
Labels: bug

#1154 Fix CI badge in README
  README.md
Labels: documentation

#1159 Clarify documentation for `link-href-attributes` rule
  docs/rule/link-href-attributes.md
Labels: documentation

#1120 Add new rule `no-invalid-link-title`
  docs/rule/no-invalid-link-title.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-invalid-link-title.js
  test/unit/rules/no-invalid-link-title-test.js
Labels: enhancement

#1105 Add new rule: `require-input-label`
  docs/rule/require-input-label.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/require-input-label.js
  test/unit/rules/require-input-label-test.js
Labels: enhancement

#1167 Ensure accessing `this.editorConfig` in a rule instance does not error.
  lib/linter.js
  lib/rules/base.js
  test/helpers/fake-project.js
  test/unit/base-plugin-test.js
Labels: bug

#1166 Refactor `cli-test.js` to remove usage of fixtures in favor of using fake project
  test/acceptance/cli-test.js
  test/fixtures/rules-subset-disabled/application.hbs
  test/fixtures/rules-subset-disabled/temp-templatelint-rc.js
  test/fixtures/rules-subset/temp-templatelint-rc.js
  test/fixtures/rules-subset/template.hbs
  test/fixtures/stdin-with-errors/.template-lintrc.js
  test/fixtures/stdin-with-errors/app/templates/application.hbs
  test/fixtures/with-errors-and-warnings/.template-lintrc.js
  test/fixtures/with-errors-and-warnings/app/templates/application.hbs
  test/fixtures/with-errors/.template-lintrc.js
  test/fixtures/with-errors/app/templates/application.hbs
  test/fixtures/with-partially-passing-pending-modules/.template-lintrc.js
  test/fixtures/with-partially-passing-pending-modules/app/templates/application.hbs
  test/fixtures/with-passing-pending-modules/.template-lintrc.js
  test/fixtures/with-passing-pending-modules/app/templates/application.hbs
  test/fixtures/with-warnings/.template-lintrc.js
  test/fixtures/with-warnings/app/templates/application.hbs
  test/fixtures/without-errors/.editorconfig
  test/fixtures/without-errors/.template-lintrc.js
  test/fixtures/without-errors/app/templates/application.hbs
Labels: internal

#1102 Add new rule `no-heading-inside-button`
  docs/rule/no-heading-inside-button.md
  docs/rules.md
  lib/rules/index.js
  lib/rules/no-heading-inside-button.js
  test/unit/rules/no-heading-inside-button-test.js
Labels: enhancement

#1074 feat(cli-option): Add --help option and configurable option parsing
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
Labels: enhancement

#1169 Add support to `test.only` in the test harness.
  lib/helpers/rule-test-harness.js
  test/helpers/rule-test-harness.js
Labels: enhancement

#1173 Update minimum version of ember-template-recast to 4.1.1.
  package.json
  yarn.lock
Labels: internal

#1174 Add test harness features (naming test cases, snapshot support, etc).
  lib/helpers/rule-test-harness.js
  test/acceptance/__snapshots__/rule-test.js.snap
  test/acceptance/rule-test.js
Labels: enhancement

#1158 Introduce rule visitor based fixing support.
  lib/helpers/rule-test-harness.js
  lib/linter.js
  lib/rules/base.js
  test/acceptance/rule-test.js
Labels: enhancement

#1178 require-button-type: Implement `fix` mode
  lib/rules/require-button-type.js
  test/unit/rules/require-button-type-test.js
Labels: enhancement
