Repository ember-template-lint/ember-template-lint, pull requests merged in 2020-12, with the labels that each got.

#1623 Implement `splat-attributes-only` rule
  README.md
  docs/rule/splat-attributes-only.md
  lib/rules/index.js
  lib/rules/splat-attributes-only.js
  test/unit/rules/splat-attributes-only-test.js
Labels: enhancement

#1630 Add element examples to `no-duplicate-attributes`
  docs/rule/no-duplicate-attributes.md
Labels: documentation

#1638 Add more rules to `stylistic` config
  README.md
  docs/rule/modifier-name-case.md
  docs/rule/no-whitespace-for-layout.md
  docs/rule/no-whitespace-within-word.md
  lib/config/stylistic.js
Labels: breaking

#1639 Promote `octane` rules to `recommended` config and delete `octane` config
  README.md
  docs/rule/no-action.md
  docs/rule/no-curly-component-invocation.md
  docs/rule/no-implicit-this.md
  lib/config/index.js
  lib/config/octane.js
  lib/config/recommended.js
  scripts/update-rules.js
  test/helpers/fake-project.js
  test/unit/recommended-config-test.js
  test/unit/rule-setup-test.js
Labels: breaking

#1642 Update `noImplicitThis` option default to true and `requireDash` option default to false in `no-curly-component-invocation` rule
  docs/rule/no-curly-component-invocation.md
  lib/config/recommended.js
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: breaking

#1643 Enable more `recommended` rules
  README.md
  docs/rule/builtin-component-arguments.md
  docs/rule/deprecated-each-syntax.md
  docs/rule/deprecated-inline-view-helper.md
  docs/rule/no-accesskey-attribute.md
  docs/rule/no-arguments-for-html-elements.md
  docs/rule/no-aria-hidden-body.md
  docs/rule/no-block-params-for-html-elements.md
  docs/rule/no-duplicate-id.md
  docs/rule/no-duplicate-landmark-elements.md
  docs/rule/no-forbidden-elements.md
  docs/rule/no-heading-inside-button.md
  docs/rule/no-invalid-block-param-definition.md
  docs/rule/no-invalid-link-title.md
  docs/rule/no-nested-landmark.md
  docs/rule/no-nested-splattributes.md
  docs/rule/no-passed-in-event-handlers.md
  docs/rule/no-positional-data-test-selectors.md
  docs/rule/no-potential-path-strings.md
  docs/rule/no-redundant-fn.md
  docs/rule/no-redundant-landmark-role.md
  docs/rule/no-unbalanced-curlies.md
  docs/rule/no-yield-only.md
  docs/rule/require-input-label.md
  docs/rule/require-lang-attribute.md
  docs/rule/splat-attributes-only.md
  lib/config/recommended.js
Labels: breaking

#1606 Fix false positive with content within `{{#if}}`/`{{else}}` blocks in `no-duplicate-id` rule
  lib/rules/no-duplicate-id.js
  test/unit/rules/no-duplicate-id-test.js
Labels: bug

#1596 Add new rule `no-model-argument-in-route-templates`
  README.md
  docs/rule/no-model-argument-in-route-templates.md
  lib/rules/index.js
  lib/rules/no-model-argument-in-route-templates.js
  test/unit/rules/no-model-argument-in-route-templates-test.js
Labels: enhancement

#1647 Enable `no-model-argument-in-route-templates` as a `recommended` rule
  README.md
  docs/rule/no-model-argument-in-route-templates.md
  lib/config/recommended.js
Labels: breaking

#1653 Adds auto-fix for `no-redundant-landmark-role` rule
  README.md
  docs/rule/no-redundant-landmark-role.md
  lib/rules/no-redundant-landmark-role.js
  test/unit/rules/no-redundant-landmark-role-test.js
Labels: enhancement

#1652 Add `no-mut-helper` rule
  README.md
  docs/rule/no-action.md
  docs/rule/no-extra-mut-helper-argument.md
  docs/rule/no-mut-helper.md
  lib/rules/index.js
  lib/rules/no-mut-helper.js
  test/unit/rules/no-mut-helper-test.js
Labels: enhancement

#1611 Implements new todo functionality (replaces pending)
  bin/ember-template-lint.js
  lib/-private/todo-handler.js
  lib/get-config.js
  lib/helpers/process-results.js
  lib/linter.js
  lib/printers/json.js
  lib/printers/pretty.js
  package.json
  test/acceptance/cli-test.js
  test/helpers/fake-project.js
  test/printers/pretty-test.js
  yarn.lock
Labels: enhancement

#1664 Reorganizes and updates the README
  README.md
  docs/configuration.md
  docs/node-api.md
Labels: documentation
