Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-10, with the labels that each got.

#2119 Stricter validation of rule doc notices
  docs/rule/no-positional-data-test-selectors.md
  docs/rule/no-redundant-fn.md
  docs/rule/no-redundant-landmark-role.md
  docs/rule/no-this-in-template-only-components.md
  docs/rule/require-has-block-helper.md
  test/unit/rule-setup-test.js
Labels: documentation

#2013 Add `Textarea` support to `builtin-component-arguments` rule
  docs/rule/builtin-component-arguments.md
  lib/rules/builtin-component-arguments.js
  test/unit/rules/builtin-component-arguments-test.js
Labels: enhancement

#2118 Add autofixer to `no-negated-condition` rule
  README.md
  docs/rule/no-negated-condition.md
  lib/rules/no-negated-condition.js
  test/unit/rules/no-negated-condition-test.js
Labels: enhancement

#1861 Fix false positive with local `log` in `no-log` rule
  lib/rules/no-log.js
  test/unit/rules/no-log-test.js
Labels: bug

#1864 Add `has-block-params` as built-in helper to `no-implicit-this` rule
  lib/rules/no-implicit-this.js
Labels: bug

#1841 Add new rule `no-with`
  README.md
  docs/rule/no-with.md
  lib/rules/no-with.js
  test/unit/rules/no-with-test.js
Labels: enhancement

#1955 Add new rule `no-valueless-arguments`
  README.md
  docs/rule/no-valueless-arguments.md
  lib/rules/no-valueless-arguments.js
  test/unit/rules/no-valueless-arguments-test.js
Labels: enhancement

#1851 Fix false positive with slash symbol in `no-unbound` rule
  lib/rules/no-unbalanced-curlies.js
  test/unit/rules/no-unbalanced-curlies-test.js
Labels: bug

#636 Add new rule `require-context-role`
  README.md
  docs/rule/require-context-role.md
  lib/config/a11y.js
  lib/rules/require-context-role.js
  test/unit/rules/require-context-role-test.js
Labels: enhancement

#1935 Add autofixer to `no-unknown-arguments-for-builtin-components` rule
  README.md
  docs/rule/no-unknown-arguments-for-builtin-components.md
  lib/rules/no-unknown-arguments-for-builtin-components.js
  test/unit/rules/no-unknown-arguments-for-builtin-components-test.js
Labels: enhancement

#1934 Fix false positives in `deprecated-inline-view-helper` rule
  lib/rules/deprecated-inline-view-helper.js
  test/unit/rules/deprecated-inline-view-helper-test.js
Labels: bug

#1982 Add new rule `require-presentational-children`
  README.md
  docs/rule/require-presentational-children.md
  lib/config/a11y.js
  lib/helpers/ast-node-info.js
  lib/rules/no-abstract-roles.js
  lib/rules/require-presentational-children.js
  test/unit/rules/require-presentational-children-test.js
Labels: enhancement, a11y

#2053 Add `labelTags` option for custom label components to `require-input-label` rule
  docs/rule/require-input-label.md
  lib/rules/require-input-label.js
  test/unit/rules/require-input-label-test.js
Labels: enhancement, a11y

#2157 Ensure rules with options include a `Configuration` section in their rule doc
  lib/rules/no-html-comments.js
  lib/rules/no-triple-curlies.js
  test/unit/rule-setup-test.js
Labels: documentation
