Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-01, with the labels that each got.

#1668 Remove explicit GitHub Actions reporter
  README.md
  lib/printers/default.js
  lib/printers/github-actions.js
  test/acceptance/cli-test.js
  test/acceptance/editors-integration-test.js
  test/acceptance/stdin-by-platform-test.js
  test/unit/github-actions-test.js
Labels: bug

#1676 Fix documentation issues
  docs/configuration.md
  docs/overrides.md
Labels: documentation

#1657 Add example script for counting lint violation disable directive comments
  docs/configuration.md
  docs/count-lint-violations.sh
Labels: documentation

#1666 Add documentation for TODOs
  README.md
  docs/configuration.md
  docs/todos.md
Labels: documentation

#1356 Add new rule: `no-yield-to-default`
  README.md
  docs/rule/no-yield-to-default.md
  lib/rules/index.js
  lib/rules/no-yield-to-default.js
  test/unit/rules/no-yield-to-default-test.js
Labels: enhancement

#1687 Respect extends order and rules overrides
  lib/get-config.js
  test/unit/-private/module-status-cache-test.js
  test/unit/get-config-test.js
Labels: bug

#1689 Removes complexity and no-return-await rules
  .eslintrc.js
  lib/rules/base.js
  lib/rules/block-indentation.js
  lib/rules/no-curly-component-invocation.js
  lib/rules/no-invalid-meta.js
  lib/rules/no-negated-condition.js
  lib/rules/require-valid-alt-text.js
Labels: internal

#1688 Adds output feedback when creating TODOs
  .eslintrc.js
  bin/ember-template-lint.js
  lib/-private/todo-handler.js
  lib/linter.js
  lib/printers/default.js
  lib/printers/pretty.js
  package.json
  test/acceptance/cli-test.js
  yarn.lock
Labels: enhancement

#1683 Update error message for resolved todos
  lib/-private/todo-handler.js
  test/acceptance/cli-test.js
Labels: bug

#1694 Add `no-down-event-binding` to A11Y config
  lib/config/a11y.js
Labels: breaking

#1695 todos: Standardize casing for todos
  README.md
  docs/configuration.md
  docs/todos.md
  package.json
  test/acceptance/cli-test.js
  yarn.lock
Labels: bug, documentation

#1700 Fix `lint:docs` syntax on Windows
  package.json
Labels: internal

#1388 Remove automatic `TextNode` unwrapping by `attributeValue` functions in `ast-node-info` helper
  lib/helpers/ast-node-info.js
  lib/rules/no-heading-inside-button.js
  lib/rules/no-invalid-link-title.js
  lib/rules/no-invalid-meta.js
  lib/rules/no-invalid-role.js
  lib/rules/no-nested-landmark.js
  lib/rules/no-redundant-landmark-role.js
  lib/rules/require-lang-attribute.js
  lib/rules/require-valid-alt-text.js
Labels: breaking

#1702 Update `stylistic` config emoji
  README.md
  docs/rule/block-indentation.md
  docs/rule/eol-last.md
  docs/rule/linebreak-style.md
  docs/rule/no-multiple-empty-lines.md
  docs/rule/no-trailing-spaces.md
  docs/rule/no-unnecessary-concat.md
  docs/rule/quotes.md
  docs/rule/self-closing-void-elements.md
  scripts/update-rules.js
  test/unit/rule-setup-test.js
Labels: internal

#1671 Add rule: `no-this-in-template-only-components`
  README.md
  docs/rule/no-this-in-template-only-components.md
  lib/rules/index.js
  lib/rules/no-this-in-template-only-components.js
  test/unit/rules/no-this-in-template-only-components-test.js
Labels: enhancement

#1697 Allow rule visitor to be an async function (remove `env` argument)
  lib/linter.js
  lib/rules/base.js
  test/acceptance/rule-test.js
  test/unit/base-plugin-test.js
Labels: breaking

#1706 Fixes todo creation messaging to include correct counts
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
Labels: bug

#1710 Adds `octane` config back as an alias of `recommended`
  lib/config/index.js
  lib/config/octane.js
Labels: enhancement

#1711 Add missing changes to 3.0.0-beta.1 CHANGELOG
  CHANGELOG.md
Labels: documentation

#1715 Prevent todo removal when using `--update-todo` a subset of normal project configuration
  bin/ember-template-lint.js
  lib/-private/todo-handler.js
  lib/linter.js
  package.json
  test/acceptance/cli-test.js
  yarn.lock
Labels: bug

#1716 Add `no-dynamic-subexpression-invocations`.
  README.md
  docs/rule/no-dynamic-subexpression-invocations.md
  lib/rules/index.js
  lib/rules/no-dynamic-subexpression-invocations.js
  test/unit/rules/no-dynamic-subexpression-invocations-test.js
Labels: enhancement

#1719 Fixes todo creation/removal when using scoped configurations.
  bin/ember-template-lint.js
  lib/-private/todo-handler.js
  lib/linter.js
  package.json
  test/acceptance/cli-test.js
  yarn.lock
Labels: bug

#1722 No invalid roles fatal error fix
  lib/rules/no-invalid-role.js
  test/unit/rules/no-invalid-role-test.js
Labels: bug

#1714 Update recommended config to include 'no-down-event-binding'
  README.md
  docs/rule/no-down-event-binding.md
  lib/config/recommended.js
Labels: breaking
