Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-11, with the labels that each got.

#2156 Move workflow examples out of README into separate doc
  README.md
  docs/todos.md
  docs/workflow.md
Labels: documentation

#2162 Ensure test harness setup in custom plugins is correct
  lib/helpers/rule-test-harness.js
  test/acceptance/rule-test.js
Labels: enhancement

#2164 Noops the console when using the SARIF formatter
  bin/ember-template-lint.js
Labels: bug

#2165 Adding ruleId to deprecation message to track its origin
  lib/rules/_base.js
Labels: bug

#2167 Slightly loosening requires for log method parameter requirements
  lib/rules/_base.js
Labels: bug

#2174 Fix false negative with `always` setting and template ending with non-text in `eol-last` rule
  lib/rules/eol-last.js
  test/unit/rules/eol-last-test.js
Labels: bug

#2175 Ensure minimum test code coverage enforced
  package.json
Labels: internal

#2168 Add new rule `no-autofocus-attribute`
  README.md
  docs/rule/no-autofocus-attribute.md
  lib/config/a11y.js
  lib/rules/no-autofocus-attribute.js
  test/unit/rules/no-autofocus-attribute-test.js
Labels: enhancement

#2188 Delete rule `no-invalid-block-param-definition`
  README.md
  docs/rule/no-invalid-block-param-definition.md
  docs/rule/no-shadowed-elements.md
  lib/config/recommended.js
  lib/rules/no-invalid-block-param-definition.js
  test/unit/rules/no-invalid-block-param-definition-test.js
Labels: breaking

#2176 Require Node `^12.22.0 || ^14.17.0 || >=16.0.0`
  .github/workflows/ci.yml
  README.md
  lib/formatters/default.js
  lib/helpers/javascript.js
  lib/rules/require-presentational-children.js
  lib/rules/table-groups.js
  package.json
  test/unit/helpers/javascript-test.js
Labels: breaking

#2191 Delete rule `deprecated-each-syntax`
  README.md
  docs/rule/deprecated-each-syntax.md
  lib/rules/deprecated-each-syntax.js
  test/unit/rules/deprecated-each-syntax-test.js
Labels: breaking

#2192 Delete config `octane`
  lib/config/octane.js
Labels: breaking

#2195 Set `allowEmptyLinks` option default to `false` on `no-invalid-link-text` rule
  docs/rule/no-invalid-link-text.md
  lib/rules/no-invalid-link-text.js
  test/unit/rules/no-invalid-link-text-test.js
Labels: breaking

#2193 Remove `--json` CLI option
  bin/ember-template-lint.js
  docs/workflow.md
  lib/formatters/default.js
  test/acceptance/cli-test.js
  test/acceptance/editors-integration-test.js
  test/unit/bin/parse-argv-test.js
Labels: breaking

#1881 Check for link title being substring of link text in `no-invalid-link-title` rule
  docs/rule/no-invalid-link-title.md
  lib/rules/no-invalid-link-title.js
  test/unit/rules/no-invalid-link-title-test.js
Labels: bug, breaking

#2172 Upgrade ember-template-recast to v6
  package.json
  test/unit/rules/no-bare-strings-test.js
  yarn.lock
Labels: breaking

#2200 chore(dev-deps): update yeoman-test to v6
  package.json
  yarn.lock
Labels: dependencies

#2210 Ensure `--print-pending` works with `--format=json` in addition to `--json`
  bin/ember-template-lint.js
  docs/workflow.md
Labels: bug

#2089 Ensure `no-bare-strings` checks the arguments to `{{page-title ...}}` helper
  lib/rules/no-bare-strings.js
  test/unit/rules/no-bare-strings-test.js
Labels: breaking

#2215 Fix Node version on CI
  .github/workflows/ci.yml
Labels: internal

#2208 Add `exports` to package.json
  package.json
Labels: breaking

#2209 Expose `generateRuleTests` as named export in public NodeJS API
  docs/node-api.md
  docs/plugins.md
  lib/index.js
Labels: enhancement

#2216 Disallow unexpected properties in rule test cases
  lib/helpers/rule-test-harness.js
  lib/rules/no-outlet-outside-routes.js
  test/acceptance/rule-test.js
  test/helpers/rule-test-harness.js
  test/unit/rules/no-outlet-outside-routes-test.js
  test/unit/rules/self-closing-void-elements-test.js
Labels: breaking

#2217 Require auto-fixable test cases to assert the fixed template
  lib/helpers/rule-test-harness.js
  test/acceptance/rule-test.js
  test/unit/rules/eol-last-test.js
  test/unit/rules/no-accesskey-attribute-test.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: breaking

#2211 Add additional `recommended` rules for v4
  README.md
  docs/rule/no-capital-arguments.md
  docs/rule/no-class-bindings.md
  docs/rule/no-dynamic-subexpression-invocations.md
  docs/rule/no-empty-headings.md
  docs/rule/no-link-to-tagname.md
  docs/rule/no-model-argument-in-route-templates.md
  docs/rule/no-mut-helper.md
  docs/rule/no-route-action.md
  docs/rule/no-valueless-arguments.md
  docs/rule/no-whitespace-for-layout.md
  docs/rule/no-whitespace-within-word.md
  docs/rule/no-with.md
  docs/rule/no-yield-to-default.md
  docs/rule/require-context-role.md
  docs/rule/require-presentational-children.md
  docs/rule/require-valid-named-block-naming-format.md
  lib/config/recommended.js
  lib/config/stylistic.js
Labels: breaking

#2207 Remove `--print-pending` CLI option
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
Labels: breaking

#2234 Remove unused helper `calculate-location-display`
  lib/helpers/calculate-location-display.js
Labels: internal

#2235 Remove unused helper `remove-configuration-html-comments`
  lib/helpers/remove-configuration-html-comments.js
Labels: internal

#2237 Remove config `2-x-recommended` and add `3-x-recommended` config
  lib/config/3-x-recommended.js
Labels: breaking

#2236 Disallow unexpected properties at top-level of configuration file
  lib/get-config.js
  test/unit/get-config-test.js
Labels: breaking

#2228 When logging a rule violation, require passing the node or all loc properties
  lib/rules/_base.js
  test/jest-setup.js
Labels: breaking

#2238 Disallow extending an invalid configuration
  lib/get-config.js
  test/unit/get-config-test.js
Labels: breaking

#2239 Disallow invalid plugin in configuration file
  lib/get-config.js
  test/unit/get-config-test.js
Labels: breaking

#2230 Only fixable test cases are allowed to assert `fixedTemplate`
  lib/helpers/rule-test-harness.js
  test/acceptance/rule-test.js
  test/unit/rules/eol-last-test.js
Labels: breaking

#2240 Disallow identical `template` and `fixedTemplate` in a test case
  lib/helpers/rule-test-harness.js
  test/acceptance/rule-test.js
  test/unit/rules/eol-last-test.js
Labels: breaking

#2241 Change `no-bare-strings` rule options to augment instead of replace the default config
  docs/rule/no-bare-strings.md
  lib/rules/no-bare-strings.js
  test/unit/rules/no-bare-strings-test.js
Labels: breaking

#2252 Remove deprecated pending functionality
  bin/ember-template-lint.js
  lib/-private/module-status-cache.js
  lib/get-config.js
  lib/linter.js
  test/acceptance/cli-test.js
  test/acceptance/public-api-test.js
  test/acceptance/todo-cli-test.js
  test/unit/-private/module-status-cache-test.js
Labels: breaking

#2253 Update reference links for `no-autofocus-attribute` rule
  docs/rule/no-autofocus-attribute.md
Labels: documentation

#2242 Require `message` when logging rule violation
  lib/rules/_base.js
  test/unit/base-plugin-test.js
Labels: breaking

#2143 Add autofixer to `quotes` rule
  README.md
  docs/rule/quotes.md
  lib/rules/quotes.js
  test/acceptance/public-api-test.js
  test/helpers/failure-plugin.js
  test/unit/rules/quotes-test.js
Labels: enhancement
