Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-09, with the labels that each got.

#2099 Add ember/lint keywords to package.json
  package.json
Labels: documentation

#2104 Mention package.json keywords for plugin discoverability
  docs/plugins.md
Labels: documentation

#2020 Add `--fix` support for `eol-last` rule
  README.md
  docs/rule/eol-last.md
  lib/rules/eol-last.js
  test/unit/rules/eol-last-test.js
Labels: enhancement

#2051 Bugfix: resolved issue with incorrect button type in form during template fix
  lib/rules/require-button-type.js
  test/unit/rules/require-button-type-test.js
Labels: bug

#2115 Converting --clean-todo to a default, providing --no-clean-todo option
  bin/ember-template-lint.js
  package.json
  test/acceptance/cli-test.js
  test/acceptance/todo-cli-test.js
  yarn.lock
Labels: enhancement, todos
