Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-06, with the labels that each got.

#1992 Resolved issue where test was looking for directories incorrectly
  lib/get-config.js
  test/unit/get-config-test.js
Labels: bug

#1994 Fix `require-input-label` to allow inputs within a `<label>` to have an `id` attribute
  lib/rules/require-input-label.js
  test/unit/rules/require-input-label-test.js
Labels: bug

#1997 Add `Requirements` section to README
  README.md
Labels: documentation

#1993 feat(todos): Adds support for configuring todo decay days by rule
  bin/ember-template-lint.js
  lib/formatters/pretty.js
  package.json
  test/acceptance/todo-cli-test.js
  test/helpers/fake-project.js
  yarn.lock
Labels: enhancement
