Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-03, with the labels that each got.

#1798 Refactor major version upgrade focused configurations
  lib/config/0-8-recommended.js
  lib/config/2-x-recommended.js
  lib/config/index.js
Labels: breaking

#1805 Ensure `no-unknown-arguments-for-builtin-components` allows `@query` only `<LinkTo>`'s
  lib/rules/no-unknown-arguments-for-builtin-components.js
  test/unit/rules/no-unknown-arguments-for-builtin-components-test.js
Labels: bug

#1807 Remove `deprecated-each-syntax` from `recommended` config
  README.md
  docs/rule/deprecated-each-syntax.md
  lib/config/recommended.js
Labels: bug

#1340 Feature: adds the option to provide custom formatters
  .github/workflows/ci.yml
  README.md
  bin/ember-template-lint.js
  lib/formatters/default.js
  lib/formatters/json.js
  lib/formatters/pretty.js
  lib/linter.js
  lib/printers/default.js
  test/acceptance/cli-test.js
  test/fixtures/ember-template-lint-formatter-test/index.js
  test/fixtures/ember-template-lint-formatter-test/package.json
  test/formatters/pretty-test.js
Labels: enhancement

#1822 Prevent `no-duplicate-landmark-elements` false positive for non-landmark roles
  lib/rules/no-duplicate-landmark-elements.js
  test/unit/rules/no-duplicate-landmark-elements-test.js
Labels: bug

#1824 Add missing ARIA roles to `no-invalid-role`
  lib/rules/no-invalid-role.js
Labels: bug

#1823 Fix suggestions for deprecated events and argument names in `no-unknown-built-in-component-arguments`
  lib/rules/no-unknown-arguments-for-builtin-components.js
  test/unit/rules/no-unknown-arguments-for-builtin-components-test.js
Labels: enhancement

#1810 Add rules index generator
  CONTRIBUTING.md
  dev/generate.js
  dev/new-rule-generator.js
  dev/new-rule/index.js
  dev/rules-index-generator.js
  dev/templates/doc.md
  dev/templates/rule.ejs
  dev/templates/rules-index.ejs
  dev/templates/test.ejs
  lib/rules/index.js
  package.json
  test/unit/generator-test.js
  yarn.lock
Labels: enhancement

#1832 Add `--config` example to README.md.
  README.md
Labels: documentation

#1834 Upgrading @ember-template-lint-todo-utils to 8.0.0
  package.json
  yarn.lock
Labels: dependencies

#1850 Only catch exact matches of title and link text in `no-invalid-link-title` rule
  lib/rules/no-invalid-link-title.js
  test/unit/rules/no-invalid-link-title-test.js
Labels: bug

#1857 Adding ignore option to no-passed-in-event-handlers
  docs/rule/no-passed-in-event-handlers.md
  lib/rules/no-passed-in-event-handlers.js
  test/unit/rules/no-passed-in-event-handlers-test.js
Labels: enhancement

#1862 Fix `require-has-block-helper` rule autofix when multiple parameters present
  lib/rules/require-has-block-helper.js
  test/unit/rules/require-has-block-helper-test.js
Labels: bug
