Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-04, with the labels that each got.

#1895 Updating stale todo message with more targeted --fix instructions
  lib/-private/todo-handler.js
  test/acceptance/todo-cli-test.js
Labels: enhancement

#1897 Allow words containing redundant words for `require-valid-alt-text` rule
  lib/rules/require-valid-alt-text.js
  test/unit/rules/require-valid-alt-text-test.js
Labels: bug

#1906 Fix typo in TODO documentation
  docs/todos.md
Labels: documentation

#1901 Fix invalid link in `docs/configuration.md`
  docs/configuration.md
Labels: documentation

#1904 Ensures we always emit output file even with empty results
  bin/ember-template-lint.js
  lib/formatters/default.js
  lib/formatters/json.js
  lib/formatters/pretty.js
  lib/formatters/sarif.js
  test/acceptance/cli-test.js
Labels: bug

#1907 Deprecate `--json` option in favor of `--format=json`.
  bin/ember-template-lint.js
  lib/formatters/default.js
  test/acceptance/cli-test.js
Labels: enhancement

#1919 Adds @microsoft/jest-sarif to validate SARIF file format
  package.json
  test/formatters/sarif-test.js
  test/jest-setup.js
  yarn.lock
Labels: internal

#1922 Allows SARIF output to always write to a file if outputFile is present
  lib/formatters/sarif.js
  test/formatters/sarif-test.js
Labels: bug
