Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-02, with the labels that each got.

#1725 Fixes markdown bugs in todo documentation
  docs/todos.md
Labels: documentation

#1727 Fix `no-dynamic-subexpression-invocations` handling of `{{1}}`
  lib/rules/no-dynamic-subexpression-invocations.js
  test/unit/rules/no-dynamic-subexpression-invocations-test.js
Labels: bug

#1731 Add `require-has-block-helper` lint rule
  README.md
  docs/rule/require-has-block-helper.md
  lib/rules/index.js
  lib/rules/require-has-block-helper.js
  test/unit/rules/require-has-block-helper-test.js
Labels: enhancement

#1735 Add test to `no-invalid-meta` for ember-cli default value
  test/unit/rules/no-invalid-meta-test.js
Labels: internal

#1737 Moves todo tests to their own file
  package.json
  test/acceptance/cli-test.js
  test/acceptance/todo-cli-test.js
  test/helpers/run.js
  yarn.lock
Labels: internal

#1736 Add fixer for require-has-block-helper rule
  README.md
  docs/rule/require-has-block-helper.md
  lib/rules/require-has-block-helper.js
  test/unit/rules/require-has-block-helper-test.js
Labels: enhancement

#1739 Fixes issue where todos were deleted from a different engine
  lib/linter.js
  test/acceptance/todo-cli-test.js
Labels: bug

#1747 Avoid linting `.html` files by default
  bin/ember-template-lint.js
Labels: breaking

#1749 Fixes invalid link resulting in 404 for todos docs.
  README.md
Labels: bug

#1757 Enabling require-has-block-helper in recommended
  README.md
  docs/rule/require-has-block-helper.md
  lib/config/recommended.js
Labels: breaking

#1755 Removing moduleId references in documentation
  docs/node-api.md
Labels: documentation

#1756 Remove hasBlock/hasBlockParams references in docs
  docs/rule/no-yield-to-default.md
Labels: documentation

#1672 Implement `require-splattributes` rule
  README.md
  docs/rule/require-splattributes.md
  lib/rules/index.js
  lib/rules/require-splattributes.js
  test/unit/rules/require-splattributes-test.js
Labels: enhancement

#1759 Add new rule: `no-capital-arguments`
  README.md
  docs/rule/no-capital-arguments.md
  lib/rules/index.js
  lib/rules/no-capital-arguments.js
  test/unit/rules/no-capital-arguments-test.js
Labels: enhancement

#1768 Add no-unknown-arguments-for-builtin-components to recommended
  README.md
  docs/rule/no-unknown-arguments-for-builtin-components.md
  lib/config/recommended.js
Labels: breaking

#1770 Add simplified mechanism for rules to log warnings and errors
  dev/new-rule/templates/rule.js
  docs/plugins.md
  lib/rules/base.js
  test/acceptance/rule-test.js
Labels: enhancement

#1774 Add fixer for `no-class-bindings` rule.
  README.md
  docs/rule/no-class-bindings.md
  lib/rules/no-class-bindings.js
  test/unit/rules/no-class-bindings-test.js
Labels: enhancement

#1594 Implement autofixer for `no-curly-component-invocation`
  README.md
  docs/rule/no-curly-component-invocation.md
  lib/helpers/curly-component-invocation.js
  lib/helpers/rule-test-harness.js
  lib/rules/base.js
  lib/rules/no-curly-component-invocation.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: enhancement

#1729 Make `this.filePath` and `this.workingDir` available to plugins
  lib/helpers/rule-test-harness.js
  lib/linter.js
  lib/rules/base.js
  lib/rules/no-this-in-template-only-components.js
  test/acceptance/rule-test.js
  test/unit/base-plugin-test.js
Labels: enhancement

#1785 Require Node >= 10.24
  package.json
Labels: breaking

#1788 Remove `moduleId` and `moduleName` from results
  lib/helpers/rule-test-harness.js
  lib/linter.js
  lib/rules/base.js
  lib/rules/no-attrs-in-components.js
  lib/rules/no-outlet-outside-routes.js
  test/acceptance/__snapshots__/rule-test.js.snap
  test/acceptance/cli-test.js
  test/acceptance/editors-integration-test.js
  test/acceptance/public-api-test.js
  test/acceptance/rule-test.js
  test/unit/base-plugin-test.js
  test/unit/rules/no-class-bindings-test.js
  test/unit/rules/no-dynamic-subexpression-invocations-test.js
  test/unit/rules/no-forbidden-elements-test.js
  test/unit/rules/no-model-argument-in-route-templates-test.js
  test/unit/rules/no-yield-to-default-test.js
Labels: breaking

#1787 New rule: no-link-to-positional-params
  README.md
  docs/rule/no-link-to-positional-params.md
  lib/rules/index.js
  lib/rules/no-link-to-positional-params.js
  test/unit/rules/no-link-to-positional-params-test.js
Labels: enhancement

#1789 Adding no-link-to-positional-params
  README.md
  docs/rule/no-link-to-positional-params.md
  lib/config/recommended.js
Labels: breaking

#1791 Revert no-class-binders fixer.
  README.md
  docs/rule/no-class-bindings.md
  lib/rules/no-class-bindings.js
  test/unit/rules/no-class-bindings-test.js
Labels: bug

#1790 Remove non-strict variant of link-rel-noopener
  docs/rule/link-rel-noopener.md
  lib/config/recommended.js
  lib/rules/link-rel-noopener.js
  test/unit/rules/link-rel-noopener-test.js
Labels: breaking
