Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-05, with the labels that each got.

#1918 Update some wording in README.md
  README.md
Labels: documentation

#1933 Adds `--clean-todo` option to provide separate functionality to cleanup stale and expired todos
  bin/ember-template-lint.js
  docs/todos.md
  lib/-private/todo-handler.js
  package.json
  test/acceptance/cli-test.js
  test/acceptance/todo-cli-test.js
  yarn.lock
Labels: bug, enhancement

#1900 Fixed typo in README
  README.md
Labels: documentation

#1945 Fixes `--clean-todo` flag to actually do the cleaning
  bin/ember-template-lint.js
  lib/-private/todo-handler.js
  lib/linter.js
  test/acceptance/todo-cli-test.js
Labels: bug

#1947 Moves expired todo removal under the `--clean-todo` flag
  lib/-private/todo-handler.js
  test/acceptance/todo-cli-test.js
Labels: bug

#1954 Improve columns for README rules table
  README.md
  scripts/update-rules.js
Labels: documentation
