Repository ember-template-lint/ember-template-lint, pull requests merged in 2021-12, with the labels that each got.

#2257 Update `yargs` to 17.3.0
  package.json
  test/acceptance/cli-test.js
  yarn.lock
Labels: dependencies

#2258 Update `eslint-plugin-unicorn` to v39
  lib/linter.js
  package.json
  yarn.lock
Labels: dependencies

#2255 Todos: Convert to single file storage
  bin/ember-template-lint.js
  docs/todos.md
  lib/-private/todo-handler.js
  package.json
  test/acceptance/cli-test.js
  test/acceptance/todo-cli-test.js
  yarn.lock
Labels: breaking

#2245 Exit with error when specifying non-existent file on CLI
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
  test/unit/bin/expand-file-globs-test.js
Labels: breaking

#2256 Rule Configs: Add `no-autofocus-attribute` to `recommended` config
  README.md
  docs/rule/no-autofocus-attribute.md
  lib/config/recommended.js
Labels: breaking

#2260 Updating to use @lint-todo/utils package
  bin/ember-template-lint.js
  lib/-private/todo-handler.js
  package.json
  test/acceptance/todo-cli-test.js
  yarn.lock
Labels: dependencies

#2261 Disallow unknown CLI options
  bin/ember-template-lint.js
  test/acceptance/cli-test.js
  test/unit/bin/get-possible-option-names-test.js
Labels: breaking

#2269 Add `requireActionHelper` config option to `no-element-event-actions`
  docs/rule/no-element-event-actions.md
  lib/rules/no-element-event-actions.js
  test/unit/rules/no-element-event-actions-test.js
Labels: enhancement

#2280 Remove outdated boolean config in `docs/configuration.md`
  docs/configuration.md
Labels: documentation

#2277 Updates @lint-todo/utils to latest version for read isolation
  lib/-private/todo-handler.js
  lib/linter.js
  package.json
  test/acceptance/todo-cli-test.js
  yarn.lock
Labels: bug, todos

#2279 Disallow duplicate test cases
  lib/helpers/rule-test-harness.js
  test/acceptance/rule-test.js
  test/unit/rules/attribute-indentation-test.js
  test/unit/rules/link-rel-noopener-test.js
  test/unit/rules/no-accesskey-attribute-test.js
  test/unit/rules/no-bare-strings-test.js
  test/unit/rules/no-debugger-test.js
  test/unit/rules/no-duplicate-id-test.js
  test/unit/rules/no-invalid-link-text-test.js
  test/unit/rules/no-multiple-empty-lines-test.js
  test/unit/rules/no-mut-helper-test.js
  test/unit/rules/no-restricted-invocations-test.js
  test/unit/rules/require-valid-alt-text-test.js
Labels: breaking

#2278 Disable `requireActionHelper` option on `no-element-event-actions` rule
  docs/rule/no-element-event-actions.md
  lib/rules/no-element-event-actions.js
  test/unit/rules/no-element-event-actions-test.js
Labels: breaking

#2291 Fix broken markdown links
  docs/rule/_TEMPLATE_.md
  docs/rule/no-bare-strings.md
  docs/rule/no-triple-curlies.md
  docs/rule/require-each-key.md
  docs/rule/style-concatenation.md
Labels: documentation

#2294 Update get-stdin to v9
  package.json
  yarn.lock
Labels: enhancement

#2295 Update execa to v6
  package.json
  test/acceptance/editors-integration-test.js
  test/acceptance/stdin-by-platform-test.js
  test/helpers/run.js
  yarn.lock
Labels: enhancement

#2296 Update globby to v6
  lib/helpers/cli.js
  package.json
  yarn.lock
Labels: enhancement

#2293 Update find-up to v6
  lib/get-config.js
  package.json
  yarn.lock
Labels: enhancement

#2297 Add v4 migration guide
  docs/migration/v4.md
Labels: documentation

#2302 Improve v4 migration guide
  CHANGELOG.md
  docs/migration/v4.md
Labels: documentation

#2301 Fix false positives with non-serializable rule configs in duplicate test case check
  lib/helpers/rule-test-harness.js
  test/acceptance/rule-test.js
Labels: bug

#2303 deps: Update @lint-todos/utils to fix bug with non-normalized paths
  .eslintrc.cjs
  package.json
  test/acceptance/todo-cli-test.js
  yarn.lock
Labels: bug
