Repository ember-template-lint/ember-template-lint, pull requests merged in 2022-04, with the labels that each got.

#2421 Handle dashes in `no-whitespace-within-word` rule
  lib/rules/no-whitespace-within-word.js
  test/unit/rules/no-whitespace-within-word-test.js
Labels: bug

#2435 Add CLI option `--no-error-on-unmatched-pattern`
  bin/ember-template-lint.js
  lib/helpers/cli.js
  test/acceptance/cli-test.js
Labels: enhancement

#2449 Updates `require-context-role` to accept `table` as a valid parent `role` and `rowgroup`
  docs/rule/require-context-role.md
  lib/rules/require-context-role.js
  test/unit/rules/require-context-role-test.js
Labels: bug

#2472 Fixes incorrectly invoked tests (non-awaited async)
  test/acceptance/todo-cli-test.js
  test/helpers/fake-project.js
Labels: internal

#2471 Add tests for plugin resolution within a monorepo setup
  lib/get-config.js
  test/acceptance/monorepo-test.js
  test/helpers/fake-project.js
Labels: internal

#2466 Remove validation of mustache statements in `no-invalid-aria-attributes` rule
  docs/rule/no-invalid-aria-attributes.md
  lib/rules/no-invalid-aria-attributes.js
  test/unit/rules/no-invalid-aria-attributes-test.js
Labels: bug

#2469 Add missing "forbids" sentence in `no-array-prototype-extensions` rule doc
  docs/rule/no-array-prototype-extensions.md
Labels: documentation

#2468 Ensure configuration can be resolved from a parent directory when no `--config-path` override is present (e.g. within a monorepo with `.template-lintrc.js` in the monorepo root).
  bin/ember-template-lint.js
  lib/helpers/cli.js
  test/acceptance/cli-test.js
  test/acceptance/todo-cli-test.js
  test/unit/get-config-test.js
Labels: bug

#2473 Add tests for monorepos with shared configuration in monorepo root
  test/acceptance/monorepo-test.js
Labels: internal

#2474 Ensure `--compact-todo` functions properly
  package.json
  yarn.lock
Labels: bug

#2465 Better handling of dashes in `no-whitespace-within-word` rule
  lib/rules/no-whitespace-within-word.js
  test/unit/rules/no-whitespace-within-word-test.js
Labels: bug

#2437 Standardize CLI tests with bin tester package
  .github/workflows/ci.yml
  package.json
  test/acceptance/cli-test.js
  test/acceptance/editors-integration-test.js
  test/acceptance/formatters/custom-formatters-test.js
  test/acceptance/formatters/json-test.js
  test/acceptance/formatters/multi-test.js
  test/acceptance/formatters/pretty-test.js
  test/acceptance/formatters/sarif-test.js
  test/acceptance/monorepo-test.js
  test/acceptance/public-api-test.js
  test/acceptance/stdin-by-platform-test.js
  test/acceptance/todo-cli-test.js
  test/helpers/bin-tester.js
  test/helpers/fake-project.js
  test/helpers/index.js
  test/helpers/run.js
  test/unit/base-plugin-test.js
  test/unit/bin/expand-file-globs-test.js
  test/unit/bin/get-files-to-lint-test.js
  test/unit/get-config-test.js
  test/unit/get-editor-config-test.js
  yarn.lock
Labels: internal

#2480 Test under Node 18
  .github/workflows/ci.yml
Labels: internal

#2478 Add `validateValues` option to `require-lang-attribute` rule
  docs/rule/require-lang-attribute.md
  lib/rules/require-lang-attribute.js
  package.json
  test/unit/rules/require-lang-attribute-test.js
  yarn.lock
Labels: enhancement

#2487 Add `checkAllHTMLElements` option to `no-redundant-landmark-role` rule to lint against all HTML elements with default ARIA roles
  docs/rule/no-redundant-landmark-role.md
  lib/rules/no-redundant-landmark-role.js
  test/unit/rules/no-redundant-landmark-role-test.js
Labels: enhancement
