Repository ember-template-lint/ember-template-lint, pull requests merged in 2022-08, with the labels that each got.

#2568 Add autofixer to `no-unnecessary-concat` rule
  README.md
  docs/rule/no-unnecessary-concat.md
  lib/rules/no-unnecessary-concat.js
  test/unit/rules/no-unnecessary-concat-test.js
Labels: enhancement

#2513 Update overrides example
  docs/overrides.md
Labels: documentation

#2569 Add autofixer to `require-valid-named-block-naming-format` rule
  README.md
  docs/rule/require-valid-named-block-naming-format.md
  lib/rules/require-valid-named-block-naming-format.js
  test/unit/rules/require-valid-named-block-naming-format-test.js
Labels: enhancement

#2573 Add autofixer to `modifier-name-case` rule
  README.md
  docs/rule/modifier-name-case.md
  lib/rules/modifier-name-case.js
  test/unit/rules/modifier-name-case-test.js
Labels: enhancement

#2582 Add autofixer to `no-quoteless-attributes` rule
  README.md
  docs/rule/no-quoteless-attributes.md
  lib/rules/no-quoteless-attributes.js
  package.json
  test/unit/rules/no-quoteless-attributes-test.js
Labels: enhancement

#2581 Add autofixer to `no-html-comments` rule
  README.md
  docs/rule/no-html-comments.md
  lib/rules/no-html-comments.js
  test/acceptance/cli-test.js
  test/acceptance/formatters/custom-formatters-test.js
  test/acceptance/formatters/json-test.js
  test/acceptance/formatters/pretty-test.js
  test/unit/rules/no-html-comments-test.js
Labels: enhancement

#2583 Add autofixer to `self-closing-void-elements` rule
  README.md
  docs/rule/self-closing-void-elements.md
  lib/rules/self-closing-void-elements.js
  test/unit/rules/self-closing-void-elements-test.js
Labels: enhancement

#2434 Extract `hasParentTag` utility function
  lib/helpers/has-parent-tag.js
  lib/rules/require-button-type.js
Labels: internal

#2593 Add `unique-id` to allowed built-in helpers in `no-curly-component-invocation` and `no-implicit-this` rules
  lib/rules/no-curly-component-invocation.js
  lib/rules/no-implicit-this.js
  test/unit/rules/no-curly-component-invocation-test.js
Labels: bug
