Repository ember-template-lint/ember-template-lint, pull requests merged in 2022-11, with the labels that each got.

#2669 Drop Node 12 and 17 support
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#2606 Lint embedded templates by default
  lib/helpers/cli.js
  test/acceptance/cli-test.js
Labels: breaking

#2054 Rename and narrow rule `no-down-event-binding` to `no-pointer-down-event-binding`
  README.md
  docs/rule/no-down-event-binding.md
  docs/rule/no-pointer-down-event-binding.md
  lib/config/3-x-recommended.js
  lib/config/a11y.js
  lib/config/recommended.js
  lib/rules/index.js
  lib/rules/no-pointer-down-event-binding.js
  test/unit/rules/no-pointer-down-event-binding-test.js
Labels: breaking

#2672 Change `maxHelpers` option default to `1` in `simple-unless` rule
  docs/rule/simple-unless.md
  lib/rules/simple-unless.js
  test/unit/rules/simple-unless-test.js
Labels: breaking

#2673 Change `simplifyHelpers` option default to `true` on `no-negated-condition` rule
  docs/rule/no-negated-condition.md
  lib/rules/no-negated-condition.js
  test/unit/rules/no-negated-condition-test.js
Labels: breaking

#2674 Change `validateValues` option default to `true` on `require-lang-attribute` rule
  docs/rule/require-lang-attribute.md
  lib/rules/require-lang-attribute.js
  test/unit/rules/require-lang-attribute-test.js
Labels: breaking

#2676 Refresh lockfile from scratch
  package-lock.json
Labels: internal

#2678 Use Node 18 in CI
  .github/workflows/ci.yml
  package.json
Labels: internal

#2679 Replace `3-x-recommended` config with `4-x-recommended`
  lib/config/4-x-recommended.js
  lib/config/index.js
Labels: breaking

#2680 Update jest to v29
  package-lock.json
  package.json
Labels: dependencies

#2658 feat: utilize new contents data from ember-template-imports
  lib/extract-templates.js
  package-lock.json
  package.json
Labels: internal

#2694 Use `npx` in stale todo command suggestion
  docs/todos.md
  lib/-private/todo-handler.js
  test/acceptance/todo-cli-test.js
Labels: documentation

#2698 Add CodeQL
  .github/workflows/codeql.yml
  lib/rules/no-action.js
Labels: internal

#2701 Fix autofixer for value-less attributes and comment order in `attribute-order` rule
  lib/rules/attribute-order.js
  test/unit/rules/attribute-order-test.js
Labels: bug

#2714 no-redundant-role: Allow `role=list` on `<ul>` and `<ol>`
  lib/rules/no-redundant-role.js
  test/unit/rules/no-redundant-role-test.js
Labels: bug

#2722 Fix autofixer bug with `firstObject` inside a `MustacheStatement` in `no-array-prototype-extensions`
  lib/rules/no-array-prototype-extensions.js
  test/unit/rules/no-array-prototype-extensions-test.js
Labels: bug
