Repository ember-template-lint/ember-template-lint, pull requests merged in 2022-10, with the labels that each got.

#2629 Add autofixer to `simple-unless` rule for simplest case
  README.md
  docs/rule/simple-unless.md
  lib/rules/simple-unless.js
  test/unit/rules/simple-unless-test.js
Labels: enhancement

#2636 Add link to RFC for `no-array-prototype-extensions` rule
  docs/rule/no-array-prototype-extensions.md
Labels: documentation

#2639 Add autofix for case with helpers to `simple-unless` rule
  lib/rules/simple-unless.js
  test/unit/rules/simple-unless-test.js
Labels: enhancement

#2648 Allow negation with multiple parameters in `no-negated-condition` rule
  lib/rules/no-negated-condition.js
  test/unit/rules/no-negated-condition-test.js
Labels: bug

#2659 Remove eslint-plugin-import-helpers
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: internal

#2661 Remove usage of `cross-env`
  .github/workflows/ci.yml
  package.json
Labels: internal

#2653 Add `simplifyHelpers` option in `no-negated-condition` rule
  docs/rule/no-negated-condition.md
  lib/rules/no-negated-condition.js
  test/unit/rules/no-negated-condition-test.js
Labels: enhancement
