Repository ember-template-lint/ember-template-lint, pull requests merged in 2022-03, with the labels that each got.

#2406 Relax coverage thresholds to allow for some small drift
  package.json
Labels: internal

#2401 Change formatters to return string output rather than outputting to stdout/output files
  bin/ember-template-lint.js
  lib/formatters/default.js
  lib/formatters/json.js
  lib/formatters/load-formatter.js
  lib/formatters/pretty.js
  lib/formatters/sarif.js
  lib/helpers/cli.js
  lib/helpers/write-output-file.js
  lib/linter.js
  test/acceptance/cli-test.js
  test/acceptance/formatters/custom-formatters-test.js
  test/acceptance/formatters/json-test.js
  test/acceptance/formatters/pretty-test.js
  test/acceptance/formatters/sarif-test.js
  test/fixtures/ember-template-lint-formatter-test/index.cjs
  test/formatters/pretty-test.js
  test/formatters/sarif-test.js
  test/helpers/get-output-file-contents.js
  test/helpers/index.js
Labels: internal

#2407 Update `fixturify-project` to v4
  package.json
  test/acceptance/cli-test.js
  test/acceptance/formatters/custom-formatters-test.js
  test/helpers/fake-project.js
  yarn.lock
Labels: internal

#2419 Use async `write()` instead of deprecated `writeSync()` in tests
  test/acceptance/cli-test.js
  test/acceptance/editors-integration-test.js
  test/acceptance/formatters/custom-formatters-test.js
  test/acceptance/formatters/json-test.js
  test/acceptance/formatters/multi-test.js
  test/acceptance/formatters/pretty-test.js
  test/acceptance/formatters/sarif-test.js
  test/acceptance/public-api-test.js
  test/acceptance/stdin-by-platform-test.js
  test/acceptance/todo-cli-test.js
  test/helpers/fake-project.js
  test/unit/base-plugin-test.js
  test/unit/bin/expand-file-globs-test.js
  test/unit/bin/get-files-to-lint-test.js
  test/unit/get-config-test.js
Labels: internal

#2433 Fixes require-presentational-children to return correct line/column of node
  lib/rules/require-presentational-children.js
  test/unit/rules/require-presentational-children-test.js
Labels: bug

#2413 Add new rule `no-scope-outside-table-headings`
  README.md
  docs/rule/no-scope-outside-table-headings.md
  lib/config/a11y.js
  lib/rules/index.js
  lib/rules/no-scope-outside-table-headings.js
  test/unit/rules/no-scope-outside-table-headings-test.js
Labels: enhancement
