Repository ember-template-lint/ember-template-lint, pull requests merged in 2022-05, with the labels that each got.

#2497 Add new rule `require-media-caption`
  README.md
  docs/rule/require-media-caption.md
  lib/config/a11y.js
  lib/rules/index.js
  lib/rules/require-media-caption.js
  test/unit/rules/require-media-caption-test.js
Labels: enhancement

#2505 Fixes CI OOM issues in Windows for Node 18
  .github/workflows/ci.yml
Labels: internal

#2506 Converts to using npm over yarn 1
  .github/workflows/ci.yml
  .npmrc
  CONTRIBUTING.md
  RELEASE.md
  lib/config/index.js
  lib/rules/index.js
  package-lock.json
  package.json
  scripts/update-indices.js
  test/unit/bin/get-files-to-lint-test.js
  yarn.lock
Labels: internal

#2503 Fixes issue where lint-todos add blank lines in .lint-todo storage file
  package-lock.json
  package.json
Labels: bug, dependencies

#2507 Add new rule `no-aria-unsupported-elements`
  README.md
  docs/rule/no-aria-unsupported-elements.md
  lib/config/a11y.js
  lib/rules/index.js
  lib/rules/no-aria-unsupported-elements.js
  test/unit/rules/no-aria-unsupported-elements-test.js
Labels: enhancement

#2509 Update yargs to 17.5.1 to fix `--version`
  package-lock.json
  package.json
Labels: bug

#2511 Add new rule `no-unsupported-role-attributes`
  README.md
  docs/rule/no-unsupported-role-attributes.md
  lib/config/a11y.js
  lib/rules/index.js
  lib/rules/no-unsupported-role-attributes.js
  test/unit/rules/no-unsupported-role-attributes-test.js
Labels: enhancement

#2516 Prevent `no-unsupported-role-attributes` rule from failing if the element does not have an implicit role
  lib/rules/no-unsupported-role-attributes.js
  test/unit/rules/no-unsupported-role-attributes-test.js
Labels: bug

#2523 Add new rule `require-mandatory-role-attributes`
  README.md
  docs/rule/require-mandatory-role-attributes.md
  lib/config/a11y.js
  lib/rules/index.js
  lib/rules/require-mandatory-role-attributes.js
  test/unit/rules/require-mandatory-role-attributes-test.js
Labels: enhancement
