Repository ember-template-lint/ember-template-lint, pull requests merged in 2022-12, with the labels that each got.

#2727 Add note about `title` property limitations to `require-valid-alt-text` rule doc
  docs/rule/require-valid-alt-text.md
Labels: documentation

#2726 Allow passing only `@model` or `@models` for `<LinkTo>` in `no-unknown-arguments-for-builtin-components` rule
  lib/rules/no-unknown-arguments-for-builtin-components.js
  test/unit/rules/no-unknown-arguments-for-builtin-components-test.js
Labels: bug

#2730 Add autofixer to `no-duplicate-attributes` rule
  README.md
  docs/rule/no-duplicate-attributes.md
  lib/rules/no-duplicate-attributes.js
  test/unit/rules/no-duplicate-attributes-test.js
Labels: enhancement

#2731 Allow nested `menuitem`s in `no-nested-interactive` rule
  lib/rules/no-nested-interactive.js
  test/unit/rules/no-nested-interactive-test.js
Labels: bug

#2732 Link to "skipping helpers" part of the codemod doc in `no-curly-component-invocation` docs
  docs/rule/no-curly-component-invocation.md
Labels: documentation

#2725 Fix `--no-ignore-pattern`
  lib/helpers/cli.js
Labels: bug

#2746 Add autofixer to `no-multiple-empty-lines` rule
  README.md
  docs/rule/no-multiple-empty-lines.md
  lib/rules/no-multiple-empty-lines.js
  test/unit/rules/no-multiple-empty-lines-test.js
Labels: enhancement
