Repository ember-template-lint/ember-template-lint, pull requests merged in 2023-11, with the labels that each got.

#2982 Disable `modifier-name-case` for gjs/gts
  lib/config/recommended.js
Labels: bug

#1931 Add new rule `no-action-on-submit-button`
  README.md
  docs/rule/no-action-on-submit-button.md
  lib/rules/index.js
  lib/rules/no-action-on-submit-button.js
  test/unit/rules/no-action-on-submit-button-test.js
Labels: enhancement

#2990 Add rule `no-builtin-form-components`
  README.md
  docs/rule/no-builtin-form-components.md
  lib/rules/index.js
  lib/rules/no-builtin-form-components.js
  test/unit/rules/no-builtin-form-components-test.js
Labels: enhancement, New Rule
