Repository ember-template-lint/ember-template-lint, pull requests merged in 2023-01, with the labels that each got.

#2759 Improve snapshot test documentation
  docs/plugins.md
Labels: documentation

#2760 Document how to write rule test cases for fatal errors
  docs/plugins.md
Labels: documentation

#2761 Add Node v19 to CI
  .github/workflows/ci.yml
Labels: internal

#2765 Throw the more-helpful, original exception when encountering an ESM plugin/config loading error
  lib/get-config.js
  test/acceptance/public-api-test.js
Labels: bug

#2778 Ignore `unique-id` helper in `no-duplicate-id` rule
  lib/rules/no-duplicate-id.js
  test/unit/rules/no-duplicate-id-test.js
Labels: bug

#2780 Ignore `{{(unique-id)}}` helper variation in `no-duplicate-id` rule
  lib/rules/no-duplicate-id.js
  test/unit/rules/no-duplicate-id-test.js
Labels: bug
