Repository ember-template-lint/ember-template-lint, pull requests merged in 2023-02, with the labels that each got.

#2792 Add new rule `no-unnecessary-curly-parens`
  README.md
  docs/rule/no-unnecessary-curly-parens.md
  lib/rules/index.js
  lib/rules/no-unnecessary-curly-parens.js
  test/unit/rules/no-unnecessary-curly-parens-test.js
Labels: enhancement, New Rule

#2794 Add new rule `no-unnecessary-curly-strings`
  README.md
  docs/rule/no-unnecessary-curly-literals.md
  lib/rules/index.js
  lib/rules/no-unnecessary-curly-literals.js
  test/unit/rules/no-unnecessary-curly-literals-test.js
Labels: enhancement, New Rule

#2802 Rename `no-unnecessary-curly-literals` rule to `no-unnecessary-curly-strings`
  CHANGELOG.md
  README.md
  docs/rule/no-unnecessary-curly-literals.md
  docs/rule/no-unnecessary-curly-strings.md
  lib/rules/index.js
  lib/rules/no-unnecessary-curly-literals.js
  lib/rules/no-unnecessary-curly-strings.js
  test/unit/rules/no-unnecessary-curly-literals-test.js
  test/unit/rules/no-unnecessary-curly-strings-test.js
Labels: bug

#2820 Allow presentation role for `li` in `no-invalid-role` rule
  lib/rules/no-invalid-role.js
  test/unit/rules/no-invalid-role-test.js
Labels: bug

#2818 Add `additionalNonSemanticTags` option to `require-presentational-children` rule
  docs/rule/require-presentational-children.md
  lib/rules/require-presentational-children.js
  test/unit/rules/require-presentational-children-test.js
Labels: enhancement
