Repository ember-template-lint/ember-template-lint, pull requests merged in 2023-05, with the labels that each got.

#2887 Add new rule `simple-modifiers`
  README.md
  docs/rule/simple-modifiers.md
  lib/rules/index.js
  lib/rules/simple-modifiers.js
  test/unit/rules/simple-modifiers-test.js
Labels: enhancement, New Rule

#2891 Fix override for gjs files in `recommended` config
  lib/get-config.js
  test/unit/get-config-test.js
Labels: bug

#2754 Add options for different `html` / `hbs` quote styles in `quotes` rule
  docs/rule/quotes.md
  lib/rules/quotes.js
  test/unit/rules/quotes-test.js
Labels: enhancement

#2894 Add autofixer to `no-trailing-spaces` rule
  README.md
  docs/rule/no-trailing-spaces.md
  lib/rules/no-trailing-spaces.js
  test/unit/rules/no-trailing-spaces-test.js
Labels: enhancement

#2895 Add autofixer to `no-unnecessary-curly-strings` rule
  README.md
  docs/rule/no-unnecessary-curly-strings.md
  lib/rules/no-unnecessary-curly-strings.js
  test/unit/rules/no-unnecessary-curly-strings-test.js
Labels: enhancement
