Repository ember-template-lint/ember-template-lint, pull requests merged in 2025-06, with the labels that each got.

#3232 [performance] bundle bin, worker and index files
  .eslintignore
  .eslintrc.cjs
  .gitignore
  bin/source-ember-template-lint.js
  build.js
  lib/formatters/sarif.js
  lib/helpers/cli.js
  lib/helpers/country-codes.js
  lib/linter.js
  lib/rules/require-lang-attribute.js
  package-lock.json
  package.json
  scripts/update-language.js
  test/unit/rules/require-lang-attribute-test.js
Labels: enhancement, internal

#3252 chore: improve typings
  lib/helpers/ast-node-info.js
  lib/helpers/replace-node.js
  lib/helpers/scope.js
  lib/rules/_base.js
  lib/rules/linebreak-style.js
  lib/rules/types.d.ts
Labels: enhancement

#3290 Fix the ability to specify checkHbsTemplateLiterals: false in the template-lintrc to opt in to disable parsing js and ts
  bin/source-ember-template-lint.js
  lib/-private/lint-worker.js
  lib/get-config.js
  package-lock.json
  test/unit/get-config-test.js
Labels: bug

#3291 Ensured that ...attributes is listed last
  docs/rule/sort-invocations.md
  lib/rules/sort-invocations.js
  test/unit/rules/sort-invocations-test.js
Labels: bug
