Repository ember-template-lint/ember-template-lint, pull requests merged in 2025-05, with the labels that each got.

#3199 Fix broken link in docs: #3091
  docs/rule/no-builtin-form-components.md
Labels: documentation

#2422 Add `&times` to `no-bare-strings` default allow list
  lib/rules/no-bare-strings.js
Labels: bug

#2270 Add helpful assertion message when fatal test case error message doesn't match
  lib/helpers/rule-test-harness.js
Labels: enhancement

#3206 fix #1403 table-groups rule - handle enforcing order correctly when control flow helpers are used
  lib/rules/table-groups.js
  test/unit/rules/table-groups-test.js
Labels: bug

#3204 fix #2305 support "if" helper in no-bare-strings
  lib/rules/no-bare-strings.js
  test/unit/rules/no-bare-strings-test.js
Labels: bug, enhancement

#3202 fix #2462 better named blocks support in require-context-role
  lib/rules/require-context-role.js
  test/unit/rules/require-context-role-test.js
Labels: bug

#3201 fix: #2534 & #1799 - improve no-duplicate-landmark-elements
  lib/rules/no-duplicate-landmark-elements.js
  test/unit/rules/no-duplicate-landmark-elements-test.js
Labels: bug

#3200 fix #3057 improve false-positive error in no-potential-path rule
  lib/rules/no-potential-path-strings.js
  test/unit/rules/no-potential-path-strings-test.js
Labels: bug

#3196 No Spread Attributes with Class Rule
  README.md
  docs/rule/no-splattributes-with-class.md
  lib/rules/index.js
  lib/rules/no-splattributes-with-class.js
  test/unit/rules/no-splattributes-with-class-test.js
Labels: enhancement, New Rule

#3205 fix #1728 support absolute paths in no-this-in-template-only-components
  lib/rules/no-this-in-template-only-components.js
  test/unit/rules/no-this-in-template-only-components-test.js
Labels: enhancement

#3203 fix #2386 - list summary in interactive elements
  lib/helpers/is-interactive-element.js
  test/unit/rules/no-nested-interactive-test.js
Labels: enhancement

#2978 Add new rule `no-jsx-attributes`
  README.md
  docs/rule/no-jsx-attributes.md
  lib/rules/index.js
  lib/rules/no-jsx-attributes.js
  test/unit/rules/no-jsx-attributes-test.js
Labels: enhancement, New Rule

#3212 fix: Crash in block indentation auto-fixer
  lib/rules/block-indentation.js
  test/unit/rules/block-indentation-test.js
Labels: bug

#2475 Add test and implementation for plugin using `exports` in `package.json`.
  lib/get-config.js
  test/acceptance/monorepo-test.js
Labels: bug

#2867 [BUGFIX] Update no-redundant-role: Allow combobox ARIA role
  docs/rule/no-redundant-role.md
  lib/rules/no-redundant-role.js
  test/unit/rules/no-redundant-role-test.js
Labels: bug

#2491 Add Option to Print Full File Paths
  docs/workflow.md
  lib/formatters/load-formatter.js
  lib/formatters/pretty.js
  lib/helpers/cli.js
  test/acceptance/cli-test.js
  test/acceptance/formatters/pretty-test.js
Labels: enhancement

#3215 fix no-bare-strings attributes regression
  lib/rules/no-bare-strings.js
  test/unit/rules/no-bare-strings-test.js
Labels: bug

#3238 Removed remaining references to jest
  CONTRIBUTING.md
  docs/plugins.md
Labels: documentation

#3240 fix: no-this-in-template-only-components should early exit in gjs/gts (skipping this lint)
  lib/rules/no-this-in-template-only-components.js
  test/unit/rules/no-this-in-template-only-components-test.js
Labels: bug

#3243 new rule: require iframe src
  README.md
  dev/templates/rule.ejs
  docs/rule/require-iframe-src-attribute.md
  lib/rules/index.js
  lib/rules/require-iframe-src-attribute.js
  test/unit/rules/require-iframe-src-attribute-test.js
Labels: enhancement, New Rule

#3239 fix [no-bare-strings] regression
  lib/rules/no-bare-strings.js
  test/unit/rules/no-bare-strings-test.js
Labels: bug

#3245 new rule: no-chained-this
  README.md
  docs/rule/no-chained-this.md
  lib/rules/index.js
  lib/rules/no-chained-this.js
  test/unit/rules/no-chained-this-test.js
Labels: enhancement, New Rule

#3244 new rule: no-only-default-slot
  README.md
  docs/rule/no-only-default-slot.md
  lib/rules/index.js
  lib/rules/no-only-default-slot.js
  test/unit/rules/no-only-default-slot-test.js
Labels: enhancement, New Rule

#3246 improve no-bare-strings rule config
  lib/rules/no-bare-strings.js
  test/unit/rules/no-bare-strings-test.js
Labels: bug

#3198 reduce IO locks on todos
  bin/ember-template-lint.js
  lib/-private/lint-worker.js
  lib/-private/module-status-cache.js
  lib/-private/todo-handler.js
  lib/linter.js
Labels: enhancement

#1367 Add new rule: `require-valid-form-groups`
  README.md
  docs/rule/require-valid-form-groups.md
  lib/rules/index.js
  lib/rules/require-valid-form-groups.js
  test/unit/rules/require-valid-form-groups-test.js
Labels: enhancement, a11y, New Rule

#1357 Add new rule: `no-yield-block-params-to-else-inverse`
  README.md
  docs/rule/no-yield-block-params-to-else-inverse.md
  lib/rules/index.js
  lib/rules/no-yield-block-params-to-else-inverse.js
  test/unit/rules/no-yield-block-params-to-else-inverse-test.js
Labels: enhancement, New Rule
