Repository ember-template-lint/ember-template-lint, pull requests merged in 2025-02, with the labels that each got.

#3021 Remove template-imports, add content-tag, drop support for the hbs template literals from ember-template-imports (keeping support for ember-cli-htmlbars)
  .editorconfig
  .eslintrc.cjs
  .gitignore
  lib/extract-templates.js
  lib/file-types.js
  lib/helpers/cli.js
  lib/helpers/rule-test-harness.js
  lib/linter.js
  lib/template-info.js
  package-lock.json
  package.json
  test/acceptance/editors-integration-test.js
  test/acceptance/public-api-test.js
  test/unit/extract-templates-test.js
  test/unit/rules/block-indentation-test.js
  test/unit/rules/eol-last-test.js
  test/unit/rules/no-trailing-spaces-test.js
  test/unit/rules/require-button-type-test.js
  test/unit/rules/require-strict-mode-test.js
  test/unit/temp-babel-backtick-extract-test.js
Labels: breaking

#3131 Don't process ignored files
  bin/ember-template-lint.js
  lib/helpers/cli.js
  test/acceptance/cli-test.js
  test/acceptance/formatters/custom-formatters-test.js
  test/acceptance/formatters/kakoune-test.js
  test/acceptance/formatters/multi-test.js
  test/acceptance/formatters/pretty-test.js
  test/acceptance/monorepo-test.js
  test/acceptance/stdin-by-platform-test.js
  test/acceptance/todo-cli-test.js
  test/helpers/fake-project.js
  test/unit/bin/expand-file-globs-test.js
  test/unit/bin/get-files-to-lint-test.js
Labels: bug, enhancement

#3132 Fix the no-yield-only rule
  lib/rules/no-yield-only.js
  test/unit/rules/no-yield-only-test.js
Labels: bug
